/* XENOS NOTES — book module
 * To add a new book: copy this file's shape, fill in the metadata + sections, save
 * it as books/<your-slug>.js, then add one <script> line in index.html. That's it —
 * the shared engine (app.js) handles rendering, navigation, search, and styling. */
XenosBooks.register({
  slug: 'ijaz-ilmi',
  title: 'Iʿjāz ʿIlmī',
  subtitle: 'Scientific & Historical Signs in the Qurʾān and Sunnah — With Their Sources, and Their Disputes',
  icon: '🔬',
  category: 'Iʿjāz',
  arabicBg: 'الإعجاز العلمي',
  tags: ['Iʿjāz ʿIlmī', 'Tafsīr', 'Modern Science', 'Historical Miracle'],
  footer: 'Drawn from Scientific Truths in the Qurʾān (Qurʾān Project), Qurʾān and Modern Science (Dr. Zakir Naik), kaheel7.net, and peer-reviewed sources cited within',

  sections: [
    {
      id: 'intro', icon: '📖', label: 'What Is Iʿjāz ʿIlmī?', subtitle: 'A Modern Genre, Not an Ancient Consensus', color: 'var(--burgundy)',
      intro: "Iʿjāz ʿIlmī literally combines two words: iʿjāz (\"that which renders an opponent incapable of matching or responding to it\") and ʿilmī (\"of knowledge/science\"). It describes the specific claim that the Qurʾān and Sunnah contain information about the natural world that could not have been known in 7th-century Arabia and that later matches modern discovery. This book documents that claim with its real, named sources — while being honest that this is a specific, contested modern interpretive tradition, not a single settled ancient consensus.<div class='xn-diagram-wrap'><div class='xn-diagram-title' style='color:var(--burgundy)'>How Every Topic in This Book Is Built (tap each stage)</div><div class='xn-flow-wrap'><div class='xn-flow-row'><details class='xn-flow-node'><summary>📜 A Text</summary><div class='xn-flow-node-body'>A specific verse or ḥadīth, quoted in Arabic and translation, never paraphrased away from its actual wording.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>🔬 A Named Finding</summary><div class='xn-flow-node-body'>A specific modern scientist, study, or textbook — cited with author, year, and page where available — read as corroborating that wording.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>⚖️ An Honest Caveat</summary><div class='xn-flow-node-body'>Where a claim is genuinely contested — by classical exegesis, by scientists, or by the specific conditions under which a testimonial was given — this book says so explicitly, in the same section.</div></details></div></div></div>",
      bullets: [
        { label: 'Why the Qurʾān Itself Is Framed as the Central Miracle', text: "Earlier prophets were given tangible miracles (Mūsā splitting the sea, ʿĪsā raising the dead) whose full impact ended with the death of their eyewitnesses. The Qurʾān is instead framed as a permanent, testable miracle: \"And it was not [possible] for this Qurʾān to be produced by other than God... there is no doubt [it is] from the Lord of the worlds.\" (Q 10:37)" },
        { label: 'The Modern Authors Behind This Tradition', text: 'This genre is traceable to specific named 20th-century figures: Dr. Maurice Bucaille (French surgeon, "The Bible, the Qurʾān and Science," 1976), Shaykh ʿAbd al-Majeed Zindani (founder of the Commission on Scientific Signs in the Qurʾān and Sunnah), Dr. Zaghloul El-Naggar (geologist), Dr. Zakir Naik, and Abduldaem al-Kaheel (kaheel7.net) — a specific, modern interpretive movement, not a claim universally made by classical mufassirūn.' },
        { label: 'A Necessary Caution', text: "Not every claim in this genre carries equal weight. Some readings are disputed by mainstream scientists (whether a described phenomenon is actually unique), by linguists (whether a translation is the most natural one), or by other Muslim scholars (concerned about retrofitting modern science onto centuries-old exegesis). This book cites each claim's actual source so it can be weighed rather than simply accepted." },
        { label: 'What This Book Documents, Concretely', text: 'Named Qurʾānic verses and ḥadīth, the specific classical and modern commentators who read them a given way, the specific modern scientists, studies, and journals cited as corroboration (with citation detail where available), and — where it exists — the specific published counter-argument or complicating detail.' },
      ],
      qanda: [
        { q: "Why does this book distinguish the Qurʾān's own claimed miracle from the tangible miracles given to earlier Prophets?", a: "Because a tangible miracle like the splitting of the sea could only be witnessed directly by those present, and its evidentiary force ends with their generation — today it survives only as a historical report. The Qurʾān, by contrast, is a physical text anyone in any era can examine and test against their own knowledge, which is the specific sense in which this literature calls it a permanent miracle (Q 10:37)." },
        { q: 'Who are the specific named authors and scholars behind the modern Iʿjāz ʿIlmī genre, and roughly when did it develop?', a: 'It traces to Dr. Maurice Bucaille\'s 1976 book, followed by institutional efforts like Shaykh Zindani\'s Commission on Scientific Signs, and popularized further by figures like Dr. Zaghloul El-Naggar, Dr. Zakir Naik, and websites like kaheel7.net (Abduldaem al-Kaheel) — this is a 20th- and 21st-century movement, traceable to identifiable individuals and institutions, not an anonymous ancient tradition.' },
        { q: 'Why does this book include an explicit caution about contested claims rather than presenting every item as equally certain?', a: "Because presenting genuinely disputed interpretive claims as settled fact would be dishonest, and because some of this literature's specific arguments really have drawn substantive published criticism from scientists, linguists, and other Muslim scholars. Flagging that up front lets the reader weigh the strength of each individual claim rather than accepting the genre's overall confidence uncritically." },
      ],
      quiz: [
        { q: 'What two components does the term "Iʿjāz ʿIlmī" literally combine?', choices: ['"Rendering incapable of response/matching" + "of knowledge/science"', 'A term for Qurʾānic recitation style, with no connection to science', 'A specific ḥadīth collection title', 'An early Arabic grammatical term unrelated to miracles'], correct: 0 },
        { q: "Why does this book's introduction specifically distinguish the Qurʾān from Mūsā's splitting of the sea as a type of miracle?", choices: ['Because splitting the sea is considered a myth with no basis in Islamic sources', 'Because the Qurʾān is described as a permanently testable miracle, unlike a tangible miracle whose evidentiary force ended with its eyewitnesses\' generation', 'Because Mūsā is not considered a Prophet in this tradition', 'Because the Qurʾān contains an account of the sea being split as its own miracle instead'], correct: 1 },
        { q: 'Which book, published in 1976 and credited with substantially launching the modern Iʿjāz ʿIlmī genre, does this section name?', choices: ["Al-Kaheel's website archive", "Zindani's Commission report", "Bucaille's The Bible, the Qurʾān and Science", "Naik's recorded lecture series"], correct: 2 },
        { q: 'Why does this book explicitly caution readers rather than present every Iʿjāz ʿIlmī claim as equally certain?', choices: ['Because the entire genre is considered fabricated', 'Because the book\'s author personally rejects all of the claims', 'Because Islamic scholarship forbids discussing science at all', 'Because some specific claims are genuinely disputed by scientists, linguists, or other Muslim scholars, and presenting them as uniformly settled would be dishonest'], correct: 3 },
        { q: 'Which of the following is named in this section as a specific modern figure behind this tradition?', choices: ['Dr. Zaghloul El-Naggar', 'Al-Khaṭīb al-Baghdādī', 'Ibn Taymiyyah', 'Al-Ḥasan al-Baṣrī'], correct: 0 },
        { q: 'What does this book say it concretely documents, beyond just the claims themselves?', choices: ['Only the Qurʾānic verses, with no further detail', "The specific modern scientists, studies, and journals cited as corroboration, plus — where they exist — published counter-arguments or complicating details", 'Only a list of ḥadīth with no scientific cross-referencing at all', 'A complete legal ruling on whether belief in these claims is obligatory'], correct: 1 },
      ]
    },
    {
      id: 'cosmology', icon: '🌌', label: 'The Big Bang and the Smoke', subtitle: 'Q 21:30 and Q 41:11, Read Against 20th-Century Cosmology', color: 'var(--emerald)',
      intro: "Two verses are read in this literature as describing the universe's origin in terms later echoed by Big Bang cosmology — while classical exegesis, predating that cosmology entirely, read the same verses differently.<div class='xn-diagram-wrap'><div class='xn-diagram-title' style='color:var(--emerald)'>At a Glance — Ratq, Fataq, and the Smoke (tap each stage)</div><div class='xn-flow-wrap'><div class='xn-flow-row'><details class='xn-flow-node'><summary>📜 Q21:30 &amp; Q41:11</summary><div class='xn-flow-node-body'>Heavens and earth were a joined 'ratq', then 'fataqa' — torn apart; the heaven is separately described passing through 'dukhan' (smoke).</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>🔭 1922 to 1965</summary><div class='xn-flow-node-body'>Friedmann's expanding-universe math, then Lemaitre's 'primeval atom', then Hubble's 1929 redshift, then Penzias and Wilson's CMB afterglow: one joined state, torn apart, through a hot dense gaseous phase.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>⚖️ Caveat</summary><div class='xn-flow-node-body'>Classical mufassirun read ratq/fataq as rain withheld then released, or barren earth made fertile — not cosmic origins. The Big Bang reading is a modern application, not the verse's unbroken classical meaning.</div></details></div></div><div class='xn-photo-card'><img src='images/cmb-planck-allsky.jpg' alt='ESA Planck all-sky map of the cosmic microwave background' loading='lazy' /><div class='xn-photo-caption'>The Planck satellite's all-sky map of the cosmic microwave background — the afterglow light from roughly 380,000 years after the Big Bang, the observational anchor behind the dukhan (smoke) reading above.<span class='xn-photo-credit'>Credit: ESA / NASA — public domain (NASA image PIA16880)</span></div></div></div>",
      bullets: [
        { label: 'Q 21:30 — Ratq and Fataq', text: '"Have those who disbelieved not considered that the heavens and the earth were a [ratq] joined entity, and We [fataqa] separated them?" Ratq means "sewn/mixed together"; fataq means "unstitched," implying something coming into being by tearing apart a joined structure.' },
        { label: 'The Big Bang, Historically', text: "Alexander Friedmann's 1922 computations showed the universe's structure was not static; Georges Lemaître proposed a \"primeval atom\" origin; Edwin Hubble's 1929 discovery of galactic redshift established the universe is expanding; Arno Penzias and Robert Wilson's discovery of cosmic microwave background radiation closed the case for a definite beginning." },
        { label: 'Q 41:11 — Dukhān ("Smoke")', text: '"Then He directed Himself to the heaven while it was smoke..." Standard modern cosmology holds the early universe passed through an opaque, dense, hot gaseous phase before galaxies condensed out of it (cited to Weinberg, The First Three Minutes, pp. 94-105).' },
        { label: 'The Honest Caution', text: "Classical mufassirūn writing centuries before Big Bang cosmology existed offered other readings of ratq/fataq entirely unconnected to cosmic origins — for example, the heaven \"withholding\" rain and then \"releasing\" it, or the earth being infertile and then made fertile. The cosmological reading is a modern application to the verse, not the unanimous classical understanding of it." },
      ],
      qanda: [
        { q: 'What do the Arabic terms ratq and fataq mean in Q 21:30, and why does this literature connect them to the Big Bang?', a: 'Ratq means something joined, mixed, or sewn together as one entity; fataq means to unstitch or tear apart, implying a structure coming apart by force. The connection drawn is that the entire early universe\'s matter was, per Big Bang cosmology, once compressed into a single joined state before a violent event separated it — paralleling ratq followed by fataq.' },
        { q: 'What is the significance of Penzias and Wilson\'s discovery for the claim that the universe had a beginning?', a: "Their discovery of cosmic microwave background radiation — uniform low-level radiation detectable from every direction in the sky — is read as the 'afterglow' of the initial hot, dense state of the universe. It provided strong observational evidence, beyond Hubble's redshift data alone, that the universe had a genuine beginning rather than existing in an eternal steady state." },
        { q: "Why is it important that classical exegetes' readings of ratq/fataq did not connect the verse to cosmic origins?", a: "Because it shows the cosmological reading is a modern application of the verse, developed after 20th-century cosmology existed, rather than the verse's unanimous or original classical meaning. This does not by itself disprove the modern reading, but it means the claim rests on a specific modern interpretive choice, not an unbroken exegetical tradition." },
      ],
      quiz: [
        { q: 'What does the Arabic term "fataq" in Q 21:30 mean, as used in this section\'s argument?', choices: ['To illuminate or give light to something dark', 'To create ex nihilo with no prior state', 'To unstitch or tear apart a previously joined structure', 'To measure or proportion something precisely'], correct: 2 },
        { q: "Whose 1929 discovery established that galaxies are receding from each other, implying a universe in constant expansion?", choices: ['Alexander Friedmann', 'Georges Lemaître', 'Arno Penzias', 'Edwin Hubble'], correct: 3 },
        { q: 'What does the Arabic word "dukhān" in Q 41:11 mean, and what modern cosmological state is it read as describing?', choices: ["\"Smoke\" — read as the early universe's dense, hot, opaque gaseous phase before galaxies formed", '"Light" — read as the first photons emitted after the Big Bang', '"Water" — read as the primordial ocean from which life began', '"Fire" — read as the heat death of the universe billions of years from now'], correct: 0 },
        { q: "What discovery is credited with providing strong observational evidence that the universe had a genuine beginning, beyond Hubble's redshift observations alone?", choices: ["Kepler's laws of planetary motion", 'Penzias and Wilson\'s discovery of cosmic microwave background radiation', "Newton's law of universal gravitation", "Copernicus's heliocentric model"], correct: 1 },
        { q: 'What alternative, non-cosmological reading did classical mufassirūn give to ratq/fataq, according to this section?', choices: ['That the terms refer exclusively to the parting of the Red Sea', "That the terms describe the seven layers of hell", "That the heaven 'withholding' rain and then 'releasing' it, or infertile earth being made fertile", "That the terms have no meaning at all and are considered mutashābihāt (unclear verses)"], correct: 2 },
        { q: "Why does this section include the fact that classical exegesis read ratq/fataq differently from the modern cosmological reading?", choices: ['To argue the Big Bang theory itself is incorrect', 'To argue the modern reading is definitely wrong', 'Because classical exegesis is considered irrelevant to this topic', 'To honestly flag that the cosmological reading is a specific modern interpretive application, not the verse\'s unbroken classical meaning'], correct: 3 },
      ]
    },
    {
      id: 'celestial-mechanics', icon: '🪐', label: 'Orbits, a Spherical Earth, and the Sun', subtitle: "Q 21:33, Q 36:40, Q 39:5, Q 79:30", color: 'var(--gold)',
      intro: "A cluster of verses is read as describing orbital motion, a spherical (not flat) earth, the distinct nature of reflected moonlight versus self-luminous sunlight, and the sun's own eventual end.<div class='xn-diagram-wrap'><div class='xn-diagram-title' style='color:var(--gold)'>Four Verses, Four Claims (tap each one)</div><div class='xn-accordion'><details class='xn-acc-item'><summary><span>Q21:33, Q36:40 — Orbits</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>Sun, moon, night and day each 'yasbahun' (actively swim/move) in a 'falak' (orbit) — an active verb, not passive drifting.</div></details><details class='xn-acc-item'><summary><span>Q39:5 — A Round Earth</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>'Yukawwir' — the verb for winding a turban around a head — describes night wrapping over day, coherent only on a sphere.</div></details><details class='xn-acc-item'><summary><span>Q10:5, Q25:61 — Two Kinds of Light</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>The sun is always 'siraj'/'wahhaj' (self-generated light); the moon is 'munir' (reflected light) — the two terms are never swapped anywhere in the text.</div></details><details class='xn-acc-item'><summary><span>Q36:38 — An End Point</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>The sun runs 'li-mustaqarrin lahaa' — toward a fixed, determined limit — read against the sun's real, finite stellar lifespan.</div></details></div></div>",
      bullets: [
        { label: 'Orbits — Falak and Yasbaḥūn', text: '"And it is He who created the night and the day and the sun and the moon; all in an [falak] orbit are [yasbaḥūn] swimming" (Q 21:33); "It is not allowable for the sun to reach the moon, nor does the night overtake the day, but each, in an orbit, is swimming" (Q 36:40). Yasbaḥūn implies active, self-propelled motion, not mere floating.' },
        { label: 'A Spherical Earth — Kawwara and Dahā', text: '"He wraps [yukawwir] the night over the day and wraps the day over the night" (Q 39:5) — kawwara is the verb for winding a turban around a head, describing overlap only possible on a sphere. "And after that He spread [dahāhā] the earth" (Q 79:30) — dahā specifically means to spread into a rounded shape, like an ostrich egg.' },
        { label: 'Reflected Moonlight vs. Self-Luminous Sunlight', text: 'The Qurʾān consistently calls the sun sirāj ("torch"), wahhāj ("blazing lamp"), or ḍiyāʾ ("shining glory") — implying internally generated light — while calling the moon munīr, a body that gives nūr, reflected light (Q 10:5, Q 25:61, Q 71:15-16). The sun is never called nūr or munīr, nor the moon sirāj, wahhāj, or ḍiyāʾ — a consistent distinction maintained across the text.' },
        { label: "The Sun's Own Rotation and Eventual End", text: '"And the Sun runs its course for a period determined for it" (Q 36:38) — mustaqarr means a fixed, determined place or time, implying the sun\'s activity is not eternal. Separately, yasbaḥūn (Q 21:33) is read as implying the sun\'s own rotation on its axis, later confirmed by tracking sunspots, which complete a circuit roughly every 25 days.' },
      ],
      qanda: [
        { q: 'Why is the Arabic word "yasbaḥūn" significant in the orbital-motion verses, compared to a more passive verb?', a: "Yasbaḥūn derives from a root implying active self-propelled motion — the same word used for a person swimming or running, not merely floating passively. Applied to celestial bodies, it is read as implying they actively move and even rotate through space, rather than being carried along inertly, which is read as consistent with bodies that both orbit and spin on their own axes." },
        { q: 'What is the specific distinction this section draws between how the Qurʾān names the sun versus the moon?', a: 'The sun is consistently named with terms implying it generates its own light and heat (sirāj, wahhāj, ḍiyāʾ), while the moon is named munīr, specifically a body that reflects nūr (light) rather than producing it. The text never crosses these terms — the sun is never called munīr and the moon is never called sirāj — which is read as a consistent, deliberate distinction matching the actual physical difference between a self-luminous star and a reflective satellite.' },
        { q: 'What does the word "kawwara" in Q 39:5 literally describe, and why does that matter for the spherical-earth argument?', a: "Kawwara describes the act of winding a turban around someone's head — a continuous wrapping motion. Applied to night wrapping over day and day over night, this is read as only being physically coherent if the earth is a sphere (allowing continuous overlap), rather than flat (which would produce an abrupt line between night and day rather than a gradual wrap)." },
      ],
      quiz: [
        { q: 'What does the Arabic word "yasbaḥūn," used to describe celestial bodies in Q 21:33 and Q 36:40, imply about their motion?', choices: ['Active, self-propelled motion — the same root used for swimming or running', 'Passive floating with no independent motion', 'Complete stillness relative to the earth', 'Motion only visible during a solar eclipse'], correct: 0 },
        { q: 'Which two Arabic terms does this section highlight as reserved exclusively for the sun, never applied to the moon?', choices: ['Nūr and munīr', 'Sirāj/wahhāj/ḍiyāʾ — terms implying self-generated light', 'Falak and yasbaḥūn', 'Kawwara and dahā'], correct: 1 },
        { q: 'What does "kawwara" in Q 39:5 literally describe, and why is this read as implying a spherical earth?', choices: ['A term for splitting something into two flat halves', 'A term meaning to burn something to ash', 'The act of winding a turban around a head — implying continuous overlap only coherent on a sphere', 'A term describing a perfectly flat, disc-shaped surface'], correct: 2 },
        { q: "What does the Arabic word 'mustaqarr' in Q 36:38's description of the sun's course specifically imply?", choices: ['That the sun is eternal and its activity never ends', 'That the sun physically moves toward the earth over time', 'That the sun and moon are the same size', 'A fixed, determined place or time — implying the sun\'s activity has a determined endpoint'], correct: 3 },
        { q: 'What real astronomical observation is cited in this section as later confirming the sun rotates on its own axis?', choices: ['Tracking sunspots, which complete a circuit roughly every 25 days', 'The discovery of the asteroid belt', 'The measurement of solar eclipses', "Measuring the moon's distance from earth via laser reflection"], correct: 0 },
        { q: 'What does "dahā" in Q 79:30 specifically mean, according to this section, beyond a general translation of "spread"?', choices: ['To spread flat, like a carpet with no curvature', 'To spread into a rounded shape, like an ostrich egg', 'To divide into exactly seven equal layers', 'To compress into an infinitely small point'], correct: 1 },
      ]
    },
    {
      id: 'mountains', icon: '⛰️', label: 'Mountains as Pegs', subtitle: 'Q 78:6-7, Q 16:15, and Isostasy', color: 'var(--burgundy-light)',
      intro: 'Two verses describe mountains as "pegs" (awtād) and as stabilizers against the earth "shifting" — read against the 19th- and 20th-century discovery that mountains have deep roots and play a genuine role in crustal stability.<div class="xn-diagram-wrap"><div class="xn-diagram-title" style="color:var(--burgundy-light)">A Peg, Cut Away (tap to see the two halves)</div><div class="xn-flow-wrap"><div class="xn-flow-row"><details class="xn-flow-node"><summary>Above the surface</summary><div class="xn-flow-node-body">The visible peak — a small fraction of the structure, the only part a 7th-century observer could see.</div></details><span class="xn-flow-arrow">+</span><details class="xn-flow-node"><summary>Below the surface</summary><div class="xn-flow-node-body">A root reaching several times the peak’s height (Press, Earth, p.435) — matching a watad (peg), whose defining feature is that most of it is buried.</div></details><span class="xn-flow-arrow">=</span><details class="xn-flow-node"><summary>The crustal-stability role</summary><div class="xn-flow-node-body">Plate tectonics (late 1960s onward) treats this root structure as helping stabilize the crust against shifting — Q16:15’s specific claim.</div></details></div></div></div>',
      bullets: [
        { label: 'Q 78:6-7 — "Pegs"', text: '"Have We not made the earth a resting place? And the mountains as pegs (awtād)?" A peg\'s defining feature is that most of it is hidden underground, with only a small portion visible above the surface.' },
        { label: 'Mountain Roots — Frank Press\'s "Earth"', text: 'Professor Emeritus Frank Press — Science Advisor to President Jimmy Carter and 12-year President of the U.S. National Academy of Sciences — co-authored the widely used university textbook "Earth," which states that mountains have deep roots embedded in the ground, giving them a peg-like structure (Press, Earth, p. 435; diagrams p. 413).' },
        { label: 'Q 16:15 — Stabilizing Against Shifting', text: '"And He has cast into the earth firmly set mountains, lest it shift with you..." Modern plate tectonics, developed from the late 1960s onward, holds that mountains function as stabilizers of the earth\'s crust — a role only understood within that specific theoretical framework, over a millennium after the verse.' },
        { label: 'El-Naggar\'s Specific Claim', text: 'Dr. Zaghloul El-Naggar, in "The Geological Concept of Mountains in the Qurʾān," argues that mountain roots can reach several times a mountain\'s visible elevation, and that this specific role in crustal stabilization was not understood in any framework until modern plate tectonics (El-Naggar, pp. 5, 44-45).' },
      ],
      qanda: [
        { q: "Why does the Arabic word for \"peg\" (watad) specifically fit the geological structure of mountains, according to this section?", a: "Because a properly set peg has the defining feature that most of its length is buried underground, with only a small fraction visible above the surface — which matches the geological finding that mountains have deep roots extending well below the visible peak, sometimes several times the mountain's above-ground elevation." },
        { q: 'Who is Frank Press, and why does his specific credential matter to this argument?', a: 'Frank Press was Science Advisor to U.S. President Jimmy Carter and served 12 years as President of the National Academy of Sciences in Washington, DC — meaning the claim about mountain roots is not sourced to a fringe or religiously motivated author, but to a standard, mainstream geology textbook co-authored by one of the most credentialed figures in American earth science.' },
        { q: 'What specific role do mountains play according to modern plate tectonics, and when was this theory developed?', a: "Modern plate tectonics, developed from the late 1960s onward, holds that mountains help stabilize the earth's crust, resisting shifting — a specific mechanical function that was not understood within any earlier geological framework, whether classical Islamic exegesis or pre-1960s Western geology." },
      ],
      quiz: [
        { q: "What is the defining physical feature of a properly set peg (watad) that this section says matches a mountain's actual geological structure?", choices: ['That it is perfectly symmetrical on all sides', 'That it is always made of a single solid material', 'That most of its length is buried underground, with only a small portion visible above the surface', 'That it never changes shape over time'], correct: 2 },
        { q: 'Which U.S. President did Frank Press, co-author of the textbook "Earth," serve as Science Advisor to?', choices: ['Ronald Reagan', 'Richard Nixon', 'George H.W. Bush', 'Jimmy Carter'], correct: 3 },
        { q: 'According to this section, when was the modern theory of plate tectonics — including the idea that mountains stabilize the crust — developed?', choices: ['From the late 1960s onward', 'In the late 19th century', 'In the 7th century, alongside the revelation of the Qurʾān', 'It has not yet been developed as a scientific theory'], correct: 0 },
        { q: 'Who wrote "The Geological Concept of Mountains in the Qurʾān," cited in this section for the claim that mountain roots can reach several times a mountain\'s visible elevation?', choices: ['Frank Press', 'Dr. Zaghloul El-Naggar', 'Maurice Bucaille', 'Zakir Naik'], correct: 1 },
        { q: 'What does Q 16:15 specifically say mountains prevent the earth from doing?', choices: ['Cooling too quickly', 'Losing its atmosphere', 'Shifting', 'Colliding with other planets'], correct: 2 },
        { q: "Why does this section emphasize that Frank Press's textbook is a standard, mainstream university reference rather than a religious text?", choices: ['To argue that geology and religion are always in conflict', 'To argue that Frank Press personally endorsed this specific Qurʾānic reading', 'Because the textbook itself discusses the Qurʾān directly', 'To show the underlying geological claim about mountain roots rests on standard mainstream science, not a source with a religious motivation'], correct: 3 },
      ]
    },
    {
      id: 'oceans', icon: '🌊', label: 'Sea Barriers, Ocean Darkness, and Duality', subtitle: 'Q 55:19-20, Q 25:53, Q 24:40, Q 36:36', color: 'var(--emerald-light)',
      intro: 'Several verses are read as describing specific, measurable oceanographic and biological phenomena — a barrier between meeting seas, a distinct partition where fresh and salt water meet, graded darkness in the deep ocean, and universal pairing at every scale from DNA to subatomic particles.<div class="xn-diagram-wrap"><div class="xn-diagram-title" style="color:var(--emerald-light)">Four Ocean Claims, One Sea (tap each one)</div><div class="xn-accordion"><details class="xn-acc-item"><summary><span>Q55:19-20 — Two Seas Meet</span><span class="xn-acc-marker">+</span></summary><div class="xn-acc-body">Seas of different density stabilize at different depths without fully mixing — e.g. Mediterranean water sinking under Atlantic water at Gibraltar.</div></details><details class="xn-acc-item"><summary><span>Q25:53 — A Stronger Barrier Word</span><span class="xn-acc-marker">+</span></summary><div class="xn-acc-body">Fresh meeting salt water gets an extra term, "hijran mahjura" — matching the pycnocline, a genuine third zone of intermediate salinity.</div></details><details class="xn-acc-item"><summary><span>Q24:40 — Darkness Upon Darkness</span><span class="xn-acc-marker">+</span></summary><div class="xn-acc-body">Light fades from about 200m and is gone by 1000m; internal waves at layer boundaries were only found in 1904.</div></details><details class="xn-acc-item"><summary><span>Q36:36 — Pairing at Every Scale</span><span class="xn-acc-marker">+</span></summary><div class="xn-acc-body">"From that which they do not know" — read against DNA base pairs and Dirac\'s 1933 matter/antimatter duality.</div></details></div></div>',
      bullets: [
        { label: 'Q 55:19-20 — Two Seas Meeting Without Mixing', text: '"He released the two seas, meeting [side by side]; between them is a barrier [so] neither of them transgresses." Where seas of different temperature, salinity, and density meet (e.g., Mediterranean water entering the Atlantic over the Gibraltar sill), the two bodies stabilize at different depths without fully mixing (Davis, Principles of Oceanography, pp. 92-93).' },
        { label: 'Q 25:53 — A Different Word for Fresh/Salt Water', text: 'When describing fresh water meeting salt water specifically, the Qurʾān adds a second term: "a barrier and prohibiting partition" (ḥijran maḥjūrā) — read against the discovery of a genuine pycnocline zone in estuaries, a distinct layer of intermediate salinity separating fresh and salt water (Gross, Oceanography, p. 242).' },
        { label: 'Q 24:40 — Layered Darkness in the Deep Sea', text: '"Darknesses within an unfathomable sea which is covered by waves, upon which are waves, over which are clouds — darknesses, some of them upon others." Light disappears by about 200m depth (where the thermocline begins) and is entirely gone by roughly 1000m; internal waves at density interfaces between water layers were only discovered in 1904 (Gross, Oceanography, p. 205).' },
        { label: 'Q 36:36 — Universal Duality/Pairing', text: '"Exalted is He who created all pairs — from what the earth grows and from themselves and from that which they do not know." Read across scales: DNA base pairs (A-T, G-C), the pairing of chromosomes, plant stamens/ovaries (discovered only ~100 years ago), and Paul Dirac\'s 1933 Nobel Prize-winning discovery of matter/antimatter duality.' },
      ],
      qanda: [
        { q: 'What is the specific oceanographic phenomenon behind the claim that two meeting seas do not mix, and where is it documented?', a: 'When bodies of water with different temperature, salinity, and density meet — such as Mediterranean water flowing into the Atlantic over the Gibraltar sill — the denser water stabilizes at a specific depth (around 1000m in that case) rather than uniformly dispersing, maintaining its own distinct characteristics for a considerable distance. This is documented in standard oceanography references such as Davis\'s Principles of Oceanography.' },
        { q: 'Why does this section highlight that the Qurʾān uses a different, stronger phrase for the divider between fresh and salt water than for the divider between two seas?', a: "Because the actual oceanographic phenomena differ: between two seas, the barrier is a stabilization at depth without a distinct intermediate zone, whereas in estuaries where fresh and salt water meet, there is a genuinely distinct third zone (the pycnocline) with its own salinity, different from both the fresh and salt water on either side — which this section reads as matching the Qurʾān's specific addition of the word 'forbidding' only in the fresh/salt water case." },
        { q: 'What does Q 36:36 claim about the scope of pairing in creation, and what is the most cited modern example given for it?', a: 'The verse claims pairing exists not only in what is directly observable (plants, animate creatures) but also "from that which they do not know" — read as anticipating pairing at scales unknown in the 7th century. The most cited modern example is DNA, whose double-helix structure is built entirely from base pairs (adenine-thymine, guanine-cytosine), discovered only with 20th-century molecular biology.' },
      ],
      quiz: [
        { q: 'What real oceanographic phenomenon is cited as the basis for the "two seas meeting without transgressing" claim in Q 55:19-20?', choices: ['Two seas of different temperature, salinity, and density stabilizing at different depths rather than uniformly mixing', 'The complete physical separation of all oceans by continental landmasses', 'The fact that seawater freezes at a different temperature than fresh water', 'Tidal patterns differing between hemispheres'], correct: 0 },
        { q: 'What specific oceanographic feature does this section say is uniquely associated with the fresh/salt water divide in Q 25:53, distinguishing it from the two-seas case in Q 55:19-20?', choices: ['A complete absence of any measurable difference between the waters', 'A genuine pycnocline zone — a distinct intermediate layer with its own salinity, different from both the fresh and salt water', 'A visible line the human eye can observe directly', 'A difference only in water temperature, with no difference in salinity'], correct: 1 },
        { q: 'At approximately what depth does this section say the thermocline begins, marking the point where the ocean starts becoming increasingly dark?', choices: ['10 meters', '5000 meters', 'About 200 meters', 'It begins at the ocean surface itself'], correct: 2 },
        { q: 'When were internal waves — occurring at density interfaces between ocean water layers — first scientifically discovered, according to this section?', choices: ['In the 7th century, alongside the Qurʾān\'s revelation', 'The 1990s', 'They remain undiscovered as of today', '1904'], correct: 3 },
        { q: 'Besides DNA base pairs, what specific 1933 Nobel Prize-winning discovery does this section cite as an example of duality at the subatomic level?', choices: ["Paul Dirac's discovery of matter/antimatter duality", "Rutherford's discovery of the atomic nucleus", "Einstein's theory of general relativity", "Bohr's model of the atom"], correct: 0 },
        { q: 'Why does Q 36:36\'s phrase "from that which they do not know" matter to the argument made in this section?', choices: ['It is read as a limitation, admitting the verse has no further scientific relevance', "It is read as anticipating forms of pairing not yet discovered at the time of revelation, later confirmed at scales like DNA and subatomic particles", 'It refers exclusively to angels and jinn, unrelated to physical pairing', 'It is considered a later scribal addition not present in the earliest manuscripts'], correct: 1 },
      ]
    },
    {
      id: 'embryology', icon: '🧬', label: "Nuṭfah to Laḥm — The Stages of the Embryo", subtitle: 'Q 23:13-14, and the Contested "Leech" Reading', color: 'var(--gold)',
      intro: "This is the single most publicly scrutinized claim in the entire Iʿjāz ʿIlmī genre. The Qurʾān names five sequential stages of embryonic development; this section documents the claim in full, including the specific scientist testimonials behind it and the specific criticism directed at how those testimonials were obtained.<div class='xn-diagram-wrap'><div class='xn-diagram-title' style='color:var(--gold)'>The Five Stages of Q23:13-14 (tap each one)</div><div class='xn-flow-wrap'><div class='xn-flow-row'><details class='xn-flow-node'><summary>1. Nutfah</summary><div class='xn-flow-node-body'>Sperm-drop, placed in a firm lodging.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>2. Alaqah</summary><div class='xn-flow-node-body'>Attached / blood-clot-like / leech-like — three classical meanings, each matching a real feature of the day-22 to 26 embryo.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>3. Mudghah</summary><div class='xn-flow-node-body'>A chewed-looking lump.</div></details></div><div class='xn-flow-row'><span class='xn-flow-trigger' style='margin-left:8px'>then</span><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>4. Izam (bones)</summary><div class='xn-flow-node-body'>Bones form first.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>5. Lahm (flesh)</summary><div class='xn-flow-node-body'>Flesh clothes the bones — the order Keith Moore's testimony highlighted.</div></details></div></div></div>",
      bullets: [
        { label: 'The Five Stages (Q 23:13-14)', text: '"Then We placed him as a sperm-drop [nuṭfah] in a firm lodging. Then We made the sperm-drop into a clinging clot [ʿalaqah], and We made the clot into a lump [muḍghah], and We made from the lump, bones [ʿiẓām], and We covered the bones with flesh [laḥm]; then We developed him into another creation."' },
        { label: 'ʿAlaqah\'s Three Meanings', text: 'Classical Arabic dictionaries give ʿalaqah three meanings: (1) attached/hanging, (2) blood clot, (3) leech. Each is read as separately matching a feature of the 22-26 day embryo: it is attached to the placenta by a connecting stalk; its external appearance resembles a blood clot due to relatively large blood volume before circulation begins; and its segmented, leech-like external shape is noted in Moore & Persaud, The Developing Human.' },
        { label: 'A Ninth-Century Christian Polemic', text: 'A Byzantine writer, Nicetas (writing 842-867 CE), used a Greek translation rendering ʿalaqah as bdella ("leech") to mock the Qurʾān\'s claim that man is created from a leech — recorded by Simelidis, "The Byzantine Understanding of the Quranic Term al-ʿalaq," Speculum 86(04), 2011, pp. 900-902. This shows the "leech" reading of ʿalaqah is not a recent invention manufactured to fit modern embryology; it is at least 1,100 years old.' },
        { label: 'The Testimonials, and the Specific Criticism of Them', text: 'Professor Keith L. Moore (University of Toronto, author of "The Developing Human") is repeatedly quoted stating the Qurʾānic embryological staging could not have been known in the 7th century. These specific statements were made in the context of conferences organized and funded by the Saudi Commission on Scientific Signs — a fact critics have pointed out means they are not the same as an independent peer-reviewed endorsement in Moore\'s own anatomy textbooks, which do not themselves argue for the Qurʾān\'s divine origin.' },
      ],
      qanda: [
        { q: 'What are the three classical dictionary meanings of ʿalaqah, and what specific embryological feature is each read as matching?', a: "Attached/hanging (the embryo clings to the endometrium via a connecting stalk, days 22-26), blood clot (the embryo's external appearance resembles a clot because it is blood-rich before circulation begins around day 21), and leech (the embryo's segmented, elongated external shape by the third week resembles a leech, and it draws nourishment from maternal blood similarly to how a leech feeds)." },
        { q: 'Why does the 9th-century polemic by Nicetas of Byzantium matter to evaluating the "leech" reading of ʿalaqah?', a: "Because it demonstrates the leech-meaning of ʿalaqah was already an established reading over a millennium ago — used, in that case, by a hostile critic trying to mock the Qurʾān rather than by a modern apologist trying to match it to embryology. This undercuts the specific accusation that the leech-reading was invented recently and retrofitted to match 20th-century microscopy." },
        { q: 'What is the specific, substantive criticism directed at the Keith Moore testimonials, distinct from simply disputing the science?', a: 'The criticism is that Moore\'s specific quotes praising the Qurʾān\'s embryology were made at conferences organized and financially supported by the Saudi Commission on Scientific Signs in the Qurʾān and Sunnah — a body with a direct interest in the outcome — rather than appearing as independent claims in his standard, peer-reviewed anatomy textbooks, which do not themselves make an argument about the Qurʾān\'s divine origin. This is a criticism about the conditions under which the endorsement was solicited, not necessarily a claim that Moore\'s specific words were fabricated.' },
      ],
      quiz: [
        { q: 'What are the five sequential stages named in Q 23:13-14, in order?', choices: ['Ṭīn, Ṣalṣāl, Ḥamaʾ, Fakhkhār, Basharan', 'Rūḥ, Nafs, Qalb, ʿAql, Jasad', 'Nuṭfah, ʿAlaqah, Muḍghah, ʿIẓām (bones), Laḥm (flesh)', 'Iman, Islam, Ihsan, Taqwa, Yaqin'], correct: 2 },
        { q: 'Which classical dictionary meaning of ʿalaqah is read as matching the embryo\'s segmented, elongated external appearance around the third week?', choices: ['Attached/hanging', 'Blood clot', 'Firm lodging', 'Leech'], correct: 3 },
        { q: "What does the 9th-century polemic by Nicetas of Byzantium, cited in this section, actually demonstrate about the 'leech' reading of ʿalaqah?", choices: ["That the reading is at least 1,100 years old, since a hostile 9th-century critic used it to mock the Qurʾān rather than to support it", "That the reading is a 20th-century invention with no older basis", "That the reading was universally rejected until Keith Moore's involvement", "That the term 'ʿalaqah' does not appear in any pre-modern source at all"], correct: 0 },
        { q: "What specific criticism does this section raise about the Keith Moore testimonials, without claiming his quoted words were fabricated?", choices: ["That Moore never actually said the quoted words in any context", "That the quotes came from conferences organized and funded by a body (the Saudi Commission on Scientific Signs) with a direct interest in the outcome, rather than from his independent, peer-reviewed textbooks", "That Moore later retracted every one of his statements in writing", "That Moore was not actually a credentialed anatomist"], correct: 1 },
        { q: 'According to this section, around what day range does the human embryo begin to take on a leech-like external appearance?', choices: ['Day 1-2', 'Day 280 (at birth)', 'Days 22-26', 'Day 100'], correct: 2 },
        { q: "Why does this section present the Keith Moore criticism at all, rather than only presenting his supportive quotes?", choices: ["To argue that Moore's embryology claims are entirely false", "Because the section argues religion and science can never be reconciled", "Because Moore is not considered a credible source on any topic", "To be transparent about the actual conditions under which the endorsement was solicited, consistent with this book's stated caution against presenting contested claims as uniformly settled"], correct: 3 },
      ]
    },
    {
      id: 'body-systems', icon: '🖐️', label: 'Fingertips, Skin, and the Frontal Lobe', subtitle: 'Q 75:3-4, Q 4:56, Q 96:15-16', color: 'var(--burgundy-deep)',
      intro: 'Three verses are read as anticipating specific, later-discovered details of human anatomy: the uniqueness of fingerprints, the skin (not deeper tissue) as the actual site of pain sensation, and the frontal lobe\'s role in governing truthful/deceptive behavior.<div class="xn-diagram-wrap"><div class="xn-diagram-title" style="color:var(--burgundy-deep)">Three Body Parts, Three Claims (tap each one)</div><div class="xn-accordion"><details class="xn-acc-item"><summary><span>Q75:3-4 — Fingertips</span><span class="xn-acc-marker">+</span></summary><div class="xn-acc-body">"Able even to proportion his fingertips" — fingerprint individuality was only documented from Purkinje (1823) to Herschel (1858) to Vucetich\'s ID system.</div></details><details class="xn-acc-item"><summary><span>Q4:56 — Skin, Not Deeper Tissue</span><span class="xn-acc-marker">+</span></summary><div class="xn-acc-body">Skin regrown "so they may taste the punishment" — matches pain receptors sitting in skin: third-degree burns (nerve endings destroyed) hurt less than shallower ones.</div></details><details class="xn-acc-item"><summary><span>Q96:15-16 — The Forelock</span><span class="xn-acc-marker">+</span></summary><div class="xn-acc-body">A "lying, sinning" forelock — read as the frontal lobe\'s role in judgment and behavior, a link first clinically noted after an 1842 railway-bar injury.</div></details></div></div>',
      bullets: [
        { label: 'Q 75:3-4 — The Uniqueness of Fingertips', text: '"Does man think that We will not assemble his bones? Yes. [We are] able [even] to proportion his fingertips." Fingerprint individuality was only scientifically documented from 1823 (Jan Purkinje\'s thesis on fingerprint patterns) through 1858 (William Herschel) to Juan Vucetich\'s formal identification system built on Alphonse Bertillon\'s 1879 anthropometric method.' },
        { label: 'Q 4:56 — The Skin as the Site of Pain', text: '"Every time their skins are roasted through We will replace them with other skins so they may taste the punishment." Anatomical study later confirmed that pain sensory nerves are concentrated specifically in the skin — in third-degree burns, where the skin\'s nerve endings are destroyed, the injured area actually feels far less pain than in a first- or second-degree burn where the skin remains intact and sensitized.' },
        { label: 'Q 96:15-16 — The "Lying, Sinning Forelock"', text: '"No! If he does not desist, We will surely drag him by the forelock [nāṣiyah] — a lying, sinning forelock." Since the front of the head has no capacity to independently lie or sin, this is read as figuratively describing the frontal lobe\'s actual function. The prefrontal cortex\'s role in personality, judgment, and behavioral initiation was only established after an 1842 [as stated in the cited source] railway accident, when a metal bar pierced a worker\'s forehead and altered his behavior while leaving other functions intact.' },
        { label: "Keith Moore's Cross-Species Point", text: 'In a 1980 joint presentation with Zaghloul El-Naggar in Cairo, Keith Moore reportedly extended the frontal-lobe argument beyond humans, stating comparative anatomy shows the nāṣiyah region functions as "the center of control and guidance" across multiple animal species with brains — read against Q 11:56: "There is no creature but that He holds its forelock."' },
      ],
      qanda: [
        { q: "Why does this section single out fingertips specifically as the example chosen in Q 75:3-4, rather than a more visually distinctive body part like the face?", a: "The section argues that a human author making the same rhetorical point about resurrection would more naturally reach for a body part associated with obvious visible distinctiveness (like the face), rather than fingertips — which are not something a 7th-century audience would have associated with uniqueness at all. The specificity of the example is read as more consistent with knowledge that fingerprints carry individually identifying detail, a fact only established through 19th- and 20th-century forensic science." },
        { q: 'What clinical detail about burn injuries is cited as supporting the specific claim that the skin, not deeper tissue, is the actual site of pain sensation?', a: "That third-degree burns — where the skin's full thickness, including its nerve endings, is destroyed — are described as causing comparatively little pain despite being the most severe injury, precisely because the pain-sensing structures have themselves been destroyed. This is read as consistent with Q 4:56's specific detail that new skin must be given in place of the old specifically so that pain can continue to be felt." },
        { q: 'What does this section say happened in 1842 that first established the frontal lobe\'s role in governing personality and behavior, and why is that detail treated with some caution?', a: "The section repeats the source's own account of a railway worker in America struck by a bar that pierced his forehead, altering his behavior while leaving his other functions intact — but this detail is presented exactly as the source states it, without independently verifying the date or identity of the individual involved, since the year given does not obviously match the most famous case of this kind reported elsewhere." },
      ],
      quiz: [
        { q: 'Whose 1823 thesis on fingerprint patterns is cited in this section as an early step in documenting fingerprint individuality?', choices: ['Jan Purkinje', 'Alphonse Bertillon', 'Juan Vucetich', 'William Herschel'], correct: 0 },
        { q: 'Why does third-degree burn injury, according to this section, actually involve comparatively less felt pain than a first- or second-degree burn?', choices: ["Because third-degree burns never damage nerve tissue", "Because the skin's nerve endings — the actual site of pain sensation — have themselves been destroyed", "Because third-degree burns are always treated with anesthesia immediately", "Because pain sensation is unrelated to which layer of tissue is injured"], correct: 1 },
        { q: 'What Arabic term in Q 96:15-16 is read as figuratively referring to the frontal lobe of the brain?', choices: ['Nafs', 'Qalb', 'Nāṣiyah', 'Rūḥ'], correct: 2 },
        { q: 'What specific 1980 event does this section cite involving Keith Moore and Zaghloul El-Naggar together?', choices: ['A joint expedition to the Dead Sea', 'A formal academic debate on the age of the universe', 'The founding of a new international medical journal', 'A joint presentation in Cairo on the cross-species function of the nāṣiyah region'], correct: 3 },
        { q: 'What does this section explicitly flag as uncertain regarding the "railway worker" story used to illustrate the discovery of frontal-lobe function?', choices: ['The exact date/details of the account, which are presented as the source states them rather than independently verified', 'Whether Keith Moore ever discussed this topic', 'Whether the Qurʾān mentions the frontal lobe at all', 'Whether the frontal lobe controls behavior at all'], correct: 0 },
        { q: 'According to this section\'s reasoning, why is a "lying, sinning forelock" considered a notable phrase rather than a straightforward literal description?', choices: ['Because the phrase is considered a later scribal insertion', 'Because the front of the head has no independent capacity to lie or commit sin, so the phrase is read as figuratively describing a brain function rather than literally accusing a body part', 'Because nāṣiyah is a word with no clear meaning at all', 'Because the phrase only appears in weak, unauthenticated manuscripts'], correct: 1 },
      ]
    },
    {
      id: 'byzantine-dead-sea', icon: '📜', label: 'The Byzantine Defeat and the Lowest Point on Earth', subtitle: 'Q 30:2-4', color: 'var(--grey-accent)',
      intro: "A specific, dated prophecy about the Byzantine-Persian war is read alongside a specific claim about the geography of where that war's battles were fought.<div class='xn-diagram-wrap'><div class='xn-diagram-title' style='color:var(--grey-accent)'>Two Claims, One Verse (tap each one)</div><div class='xn-flow-wrap'><div class='xn-flow-row'><details class='xn-flow-node'><summary>613-614 CE</summary><div class='xn-flow-node-body'>Byzantines lose Damascus and Jerusalem to Persia.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>Q30:2-4</summary><div class='xn-flow-node-body'>Predicts Byzantine victory within 3 to 9 years ('bida sinin') — publicly falsifiable at the time.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>~7 years later</summary><div class='xn-flow-node-body'>Byzantines do recover the territory, on schedule.</div></details></div><div class='xn-flow-row'><span class='xn-flow-trigger' style='margin-left:8px'>separately</span><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>'Adna' — nearest, or lowest?</summary><div class='xn-flow-node-body'>Classical reading: nearest land. The battles were fought near the Dead Sea — the lowest dry land on Earth, per USGS data.</div></details></div></div></div>",
      bullets: [
        { label: 'The Historical Setting', text: 'In 613-614 CE, the Byzantine (Eastern Roman) Empire suffered a severe defeat to the Persian Empire, losing both Damascus and Jerusalem.' },
        { label: 'Q 30:2-4 — A Specific, Time-Bound Prediction', text: '"The Byzantines have been defeated in [adnā] land. But they, after their defeat, will be victorious within a few years [biḍʿa sinīn — three to nine years]." Roughly seven years after the revelation of this verse, the Byzantines did in fact defeat the Persians and recovered the lost territory.' },
        { label: 'Adnā — "Nearest" or "Lowest"?', text: 'Classical scholars generally read adnā al-arḍ as "the nearest land" (i.e., nearest to Byzantine/Roman territory, as opposed to further-off Persia). The word adnā can also mean "lowest."' },
        { label: 'The Dead Sea as the Lowest Point on Earth', text: "The region where the decisive battles of this war were fought was around the Dead Sea — which modern geological surveys establish as the lowest point of dry land on Earth, at approximately 418 meters below sea level (U.S. Geological Survey data). This section reads the double meaning of adnā as a possible additional layer of the verse's accuracy, on top of the fulfilled seven-year prediction." },
      ],
      qanda: [
        { q: 'What specific, falsifiable prediction does Q 30:2-4 make, and how was it resolved historically?', a: 'It predicts that despite their defeat, the Byzantines would go on to defeat the Persians within three to nine years (biḍʿa sinīn). Roughly seven years after the verse\'s revelation, the Byzantine Empire did in fact defeat Persia and recover Damascus and Jerusalem — a specific, time-bound claim that was publicly testable by contemporaries in either direction, not a vague or unfalsifiable statement.' },
        { q: 'What is the double meaning of the word "adnā" in this verse, and why does this section treat it as a possible additional layer of significance?', a: "Adnā can mean either 'nearest' or 'lowest.' Classical exegesis generally favored 'nearest' (referring to territory geographically closer to Byzantine lands than deep into Persia). Modern geological surveys have separately established that the region where these battles were actually fought, around the Dead Sea, is the lowest point of dry land on Earth — so this section notes that under the 'lowest' reading, the verse's geographic description is also literally accurate, without claiming this was the primary or only intended meaning." },
      ],
      quiz: [
        { q: 'What time frame does Q 30:2-4 specifically predict for the Byzantines\' eventual victory over Persia, using the term "biḍʿa sinīn"?', choices: ['Exactly one year', 'The verse gives no specific time frame at all', 'Three to nine years', 'One hundred years'], correct: 2 },
        { q: 'Approximately how many years after the verse\'s revelation did the Byzantine Empire actually defeat Persia and recover the lost territory?', choices: ['About one year', 'It never occurred', 'About fifty years', 'About seven years'], correct: 3 },
        { q: 'What two possible meanings does the Arabic word "adnā" carry, both discussed in this section?', choices: ['"Nearest" and "lowest"', '"Ancient" and "modern"', '"Fast" and "slow"', '"Hot" and "cold"'], correct: 0 },
        { q: 'Which reading of "adnā" did classical exegetes generally favor, according to this section?', choices: ['"Lowest," referring to elevation', '"Nearest," referring to territory geographically closer to Byzantine lands', 'Neither — classical exegetes considered the word untranslatable', '"Lowest," referring to moral status'], correct: 1 },
        { q: 'What geological fact about the Dead Sea region does this section cite, based on U.S. Geological Survey data?', choices: ['It is the saltiest body of water on Earth', 'It has no measurable elevation data available', 'It is the lowest point of dry land on Earth, at approximately 418 meters below sea level', 'It is the deepest freshwater lake on Earth'], correct: 2 },
        { q: 'How does this section frame the connection between the "lowest" meaning of adnā and the Dead Sea\'s elevation?', choices: ['As a definitively proven, singular intended meaning that overrides all classical exegesis', 'As proof that the Dead Sea did not exist before this verse was revealed', 'As entirely unrelated and coincidental with no significance at all', 'As a possible additional layer of accuracy alongside the fulfilled seven-year military prediction, without claiming it was the primary classical reading'], correct: 3 },
      ]
    },
    {
      id: 'pharaoh-ramesses', icon: '👑', label: "Pharaoh's Own Words", subtitle: 'Q 79:24, Q 10:92, and the Inscriptions of Ramesses II', color: 'var(--burgundy)',
      intro: "The Qurʾān records Pharaoh's claim to be divine, and states his body would be preserved as a sign for later generations. This section documents what Ramesses II — commonly proposed by this literature as the pharaoh in question — actually inscribed about himself, while being clear about where the identification itself is interpretive rather than a settled Egyptological finding.<div class='xn-diagram-wrap'><div class='xn-diagram-title' style='color:var(--burgundy)'>Claim, Inscription, Caveat (tap each one)</div><div class='xn-flow-wrap'><div class='xn-flow-row'><details class='xn-flow-node'><summary>📜 Q79:24 &amp; Q10:92</summary><div class='xn-flow-node-body'>Pharaoh says 'I am your lord, the most high'; his body is promised preservation as a sign.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>🏛️ Abydos Inscription</summary><div class='xn-flow-node-body'>Ramesses II, in his own recorded words: 'I was Re over the people... under my sandals' (KRI II 328.6-7).</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>⚖️ Caveat</summary><div class='xn-flow-node-body'>No Egyptian record documents a drowning pursuit — that detail is only in the Quran and Torah. Identifying Ramesses II specifically is an apologetic proposal, not Egyptological consensus.</div></details></div></div></div>",
      bullets: [
        { label: "Q 79:24 — \"I Am Your Lord, the Most High\"", text: 'The Qurʾān records Pharaoh saying: "فَقَالَ أَنَا رَبُّكُمُ الْأَعْلَى" — "I am your lord, the most high!"' },
        { label: 'Q 10:92 — The Preservation of the Body', text: '"So today We will save you in your body that you may be a sign to those who succeed you." This is read as a specific claim that a particular Pharaoh\'s corpse would be physically preserved as an enduring, examinable sign.' },
        { label: "Ramesses II's Own Recorded Words", text: 'The Great Dedicatory Inscription of Ramesses II at Abydos records him declaring, in his own voice: "I was Re over the people; Upper and Lower Egyptians were under my sandals" (KRI II 328.6-7, discussed in Anthony Spalinger, The Great Dedicatory Inscription of Ramesses II: A Solar-Osirian Tractate at Abydos, Ch. 2). Elsewhere the same corpus records: "Lord of heaven, lord of earth; living Re of the entire land" (KRI II, columns 43-4).' },
        { label: 'Divine Kingship as an Institution, Not Just a Boast', text: "Andrew Collins, \"The Divinity of the Pharaoh in Greek Sources,\" Classical Quarterly 64(2): 841-844 (2014), documents that Egyptian kingship carried formal divinity through the doctrine of the \"living royal ka\" — a status renewed at coronation and again at the annual Opet festival — that continued to be applied even to foreign rulers (Darius I, Alexander the Great) well into the Ptolemaic period." },
        { label: 'The Honest Caveat on Identification', text: 'Which specific Pharaoh the Qurʾān and Torah describe is not something Egyptology itself confirms — no Egyptian record documents a pharaoh drowning in pursuit of the Israelites; that detail comes only from the Qurʾān and Torah, not from Egyptian sources, which as a matter of royal convention never recorded royal defeats. The identification with Ramesses II specifically is a common apologetic proposal (partly because his mummy was recovered largely intact in the 1881 Deir el-Bahari cache), not a claim independently established by Egyptological consensus.' },
      ],
      qanda: [
        { q: "What does Ramesses II's own inscription at Abydos actually say about his self-conception, and how does that relate to Q 79:24?", a: 'The Great Dedicatory Inscription records Ramesses II directly claiming, in his own recorded voice, "I was Re over the people; Upper and Lower Egyptians were under my sandals," and elsewhere calling himself "living Re of the entire land." This is read as historical corroboration that Egyptian pharaohs really did make exactly this kind of divine self-claim in their own inscriptions — the same category of claim the Qurʾān attributes to the Pharaoh confronting Mūsā, even though the specific individual pharaoh of the Exodus account is a separate identification question.' },
        { q: "What does Andrew Collins's academic paper establish about Egyptian divine kingship as an institution, beyond any single pharaoh's personal boasting?", a: 'It documents that pharaonic divinity was not merely rhetorical self-praise but a formal doctrine — the "living royal ka" — renewed ritually at coronation and at the annual Opet festival, and that this doctrine was applied consistently enough to be extended even to non-native rulers like the Persian king Darius I and later Alexander the Great, continuing into the Ptolemaic period. This shows the specific claim to divine status the Qurʾān records was not an isolated act of individual arrogance but reflected an entrenched state institution.' },
        { q: 'Why does this section explicitly caution that the identification of Ramesses II as "the Pharaoh of the Exodus" is not an Egyptological consensus?', a: 'Because no Egyptian inscription records a pharaoh drowning while pursuing a fleeing population — Egyptian royal inscriptions, as a matter of consistent convention, never recorded royal defeats or humiliations, so this detail is known only from the Qurʾān and the Torah, not confirmed independently from the Egyptian archaeological record. The specific identification with Ramesses II is a proposal within this apologetic literature (helped by the coincidence that his mummy survived largely intact), not something Egyptology itself has settled.' },
      ],
      quiz: [
        { q: 'What does Q 79:24 record Pharaoh saying, in his confrontation with Mūsā?', choices: ['"I am your lord, the most high"', '"I do not believe in any god"', '"There is no god but Allah"', '"I seek forgiveness from your Lord"'], correct: 0 },
        { q: 'What does Q 10:92 claim will happen to Pharaoh\'s body specifically?', choices: ['That it will be completely destroyed with no trace remaining', 'That it will be preserved as a sign for those who come after', 'That it will be transformed into stone', 'That it will be given a full royal burial with no further mention'], correct: 1 },
        { q: 'What does Ramesses II\'s own Great Dedicatory Inscription at Abydos record him saying about his own status?', choices: ['That he was a humble servant of the god Amun with no claim to divinity', 'That his father Seti I was the true living god, not himself', '"I was Re over the people; Upper and Lower Egyptians were under my sandals"', 'That he rejected all claims to divine kingship made by his predecessors'], correct: 2 },
        { q: 'According to Andrew Collins\'s paper cited in this section, how far did the doctrine of the "living royal ka" (divine kingship) extend historically?', choices: ['It ended immediately after the Old Kingdom', 'It was abolished before the New Kingdom began', 'It applied only to Ramesses II personally and no other pharaoh', 'It was applied even to non-native rulers like Darius I and Alexander the Great, continuing into the Ptolemaic period'], correct: 3 },
        { q: 'Why does this section explicitly say the identification of Ramesses II as "the Pharaoh of the Exodus" is not an Egyptological consensus?', choices: ['Because no Egyptian inscription records a pharaoh drowning in pursuit of the Israelites, since Egyptian royal records conventionally never documented royal defeats', 'Because Ramesses II is not a historically attested figure at all', 'Because Ramesses II\'s mummy has never actually been found', 'Because the Qurʾān never mentions any specific pharaoh by any description'], correct: 0 },
        { q: 'What specific archaeological event is cited as part of why Ramesses II in particular is commonly proposed for this identification?', choices: ['The discovery of the Rosetta Stone', 'The recovery of his mummy largely intact in the 1881 Deir el-Bahari cache', 'The excavation of the Great Pyramid of Giza', 'The discovery of the Dead Sea Scrolls'], correct: 1 },
      ]
    },
    {
      id: 'arabia-meadows', icon: '🏜️', label: 'The Land of Arabia Will Return to Meadows', subtitle: 'Ṣaḥīḥ Muslim 157c, and What Paleoclimate Evidence Actually Shows', color: 'var(--emerald)',
      intro: "A ḥadīth names Arabia's return to meadows and rivers as a sign preceding the Last Hour. This section documents the real paleoclimate evidence for an ancient wet Arabia — while being precise about the difference between \"Arabia was once green, in the deep geological past\" and \"the ḥadīth's specific future sign is being fulfilled now.\"<div class='xn-diagram-wrap'><div class='xn-diagram-title' style='color:var(--emerald)'>What the Evidence Shows, and What It Doesn't (tap each one)</div><div class='xn-flow-wrap'><div class='xn-flow-row'><details class='xn-flow-node'><summary>🛰️ NASA Satellite Data</summary><div class='xn-flow-node-body'>Ancient river valleys and lake basins visible beneath the Arabian sand (Phys.org, 2012).</div></details><span class='xn-flow-arrow'>+</span><details class='xn-flow-node'><summary>🦴 Fossil Record</summary><div class='xn-flow-node-body'>Late-Miocene savannahs in western Abu Dhabi, with elephant, giraffe, rhinoceros.</div></details><span class='xn-flow-arrow'>=</span><details class='xn-flow-node'><summary>⚖️ A Deep-Past Fact</summary><div class='xn-flow-node-body'>Established prehistory — millions of years ago. Not, by itself, evidence the hadith's near-term end-times sign is being fulfilled today.</div></details></div></div></div>",
      bullets: [
        { label: 'The Ḥadīth (Ṣaḥīḥ Muslim 157c)', text: 'Abū Hurayrah narrated the Prophet ﷺ said: "The Last Hour will not come before wealth becomes abundant and overflowing, so much so that a man takes zakāt out of his property and cannot find anyone to accept it from him, and till the land of Arabia reverts to meadows and rivers."' },
        { label: 'Satellite Evidence of Ancient Rivers Under the Sand', text: 'NASA satellite imagery has revealed a network of ancient river valleys and lake basins beneath the sands of the Arabian Desert. As reported by Phys.org (May 2012): "Satellite images have revealed that a network of ancient rivers once coursed their way through the sand of the Arabian Desert, leading scientists to believe that the region experienced wetter periods in the past."' },
        { label: 'Fossil Evidence of a Once-Verdant Arabia', text: 'Citing the book Extraterrestrial Sands: fossil evidence shows that in the late Miocene epoch there were lush riverine valleys in what is now western Abu Dhabi, with savannahs populated by elephant, giraffe, rhinoceros, and other large mammals. Britannica is separately cited for the fact that humans have inhabited the Arabian Desert since early Pleistocene times, roughly 2.6 million years ago, with Paleolithic sites uncovered by Saudi-sponsored archaeological research.' },
        { label: 'The Necessary Distinction', text: 'These findings describe Arabia\'s deep geological and prehistoric past — millions of years before human civilization, let alone the 7th century. The ḥadīth\'s wording describes a future event immediately preceding the Last Hour, paired with a specific and equally unfulfilled economic sign (zakāt going unaccepted for lack of poverty). Treating "Arabia was once green in prehistory" as the same claim as "the ḥadīth\'s end-times sign is now being fulfilled" conflates two different claims; the paleoclimate evidence genuinely and independently establishes the first, but does not by itself establish the second.' },
      ],
      qanda: [
        { q: 'What does the ḥadīth in Ṣaḥīḥ Muslim 157c actually pair the "return of Arabia to meadows and rivers" together with, and why does that detail matter?', a: 'It pairs the land\'s greening with wealth becoming so abundant that people can find no one poor enough to accept their zakāt — meaning the ḥadīth describes both as signs of the same approaching era, immediately preceding the Last Hour. This detail matters because it shows the greening is framed as a near-term eschatological sign occurring together with a specific, equally unfulfilled economic condition, not as an isolated claim about Arabia\'s climate at any point in history.' },
        { q: 'What specific evidence does modern satellite and fossil research actually establish about Arabia\'s climatic history?', a: "That the Arabian Peninsula was once considerably wetter, with active river systems (now visible only via satellite imagery revealing paleodrainage beneath the sand) and, in the late Miocene, savannah ecosystems supporting large mammals like elephants and giraffes in areas like western Abu Dhabi. This is well-established paleoclimatology, but it describes conditions from millions of years ago, in the geological past, not a recent or ongoing transformation." },
        { q: "Why does this section insist on distinguishing \"Arabia was once green\" from \"the ḥadīth's sign is being fulfilled now\"?", a: "Because these are logically separate claims: the first is an established fact about deep prehistory, unconnected to any prophecy, while the second would require evidence that Arabia is currently reverting to a green state in the present or near future — which is a different, much more specific claim this section does not find independently established by the same satellite and fossil evidence. Treating the two as identical would overstate what the paleoclimate evidence actually demonstrates." },
      ],
      quiz: [
        { q: 'What economic condition does Ṣaḥīḥ Muslim 157c pair together with Arabia reverting to meadows and rivers, as a joint sign of the approaching Last Hour?', choices: ['A great famine affecting the whole region', 'A drought lasting exactly seven years', 'Wealth becoming so abundant that no one can be found poor enough to accept zakāt', 'The complete disappearance of all currency'], correct: 2 },
        { q: 'What did NASA satellite imagery specifically reveal about the Arabian Desert, as reported by Phys.org in May 2012?', choices: ['That the desert has never had any water features at all', 'That the desert contains no fossil evidence of any kind', 'That the desert is currently expanding at an unprecedented rate', 'A network of ancient river valleys and lake basins beneath the sand, indicating wetter past periods'], correct: 3 },
        { q: 'According to fossil evidence cited from Extraterrestrial Sands, what kind of ecosystem existed in western Abu Dhabi during the late Miocene epoch?', choices: ['Lush riverine valleys and savannahs populated by elephant, giraffe, and rhinoceros', 'An environment identical to today\'s desert conditions', 'A deep ocean environment with no land at all', 'A frozen tundra environment'], correct: 0 },
        { q: 'Approximately how long ago does Britannica indicate humans have inhabited the Arabian Desert, according to this section?', choices: ['About 500 years', 'Since early Pleistocene times, roughly 2.6 million years ago', 'About 10,000 years', 'Humans have never inhabited the Arabian Desert'], correct: 1 },
        { q: 'What is the key distinction this section insists on regarding the paleoclimate evidence and the ḥadīth\'s claim?', choices: ['That the paleoclimate evidence is fabricated and should be disregarded', 'That the ḥadīth itself has been proven false by this evidence', "That 'Arabia was green in the deep geological past' is a separate claim from 'the ḥadīth's future end-times sign is being fulfilled now,' and the evidence directly establishes only the first", 'That the two claims are identical and the evidence fully confirms both equally'], correct: 2 },
        { q: 'Why does this section treat "Arabia was once green" and "the end-times sign is being fulfilled" as two separate claims rather than one?', choices: ['Because paleoclimate evidence is considered entirely unrelated to geography', 'Because the ḥadīth itself explicitly rules out any climatic connection', 'Because satellite imagery cannot detect anything related to water', 'Because doing otherwise would overstate what the paleoclimate evidence actually demonstrates, which concerns prehistory rather than a current or imminent transformation'], correct: 3 },
      ]
    },
    {
      id: 'fly-wings', icon: '🪰', label: "The Fly's Wings — Disease and Cure", subtitle: 'Ṣaḥīḥ al-Bukhārī 3320, and Modern Antimicrobial Research', color: 'var(--gold)',
      intro: "A ḥadīth instructs fully dipping a fly that falls into a drink, explaining that one wing carries disease and the other carries its cure. This section documents the specific modern microbiology research cited in support, including a real complicating detail in the underlying data.<div class='xn-diagram-wrap'><div class='xn-diagram-title' style='color:var(--gold)'>The Claim, the Test, the Complication (tap each one)</div><div class='xn-flow-wrap'><div class='xn-flow-row'><details class='xn-flow-node'><summary>🪰 Bukhari 3320</summary><div class='xn-flow-node-body'>Dip the whole fly in — one wing carries disease, the other its cure.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>🧪 Claresta et al. 2020</summary><div class='xn-flow-node-body'>Right-wing-treated, E. coli-contaminated water: zero measurable growth over 48h, matching a sterile control.</div></details><span class='xn-flow-arrow'>→</span><details class='xn-flow-node'><summary>⚖️ Complication</summary><div class='xn-flow-node-body'>A separate wing-microbiome survey found E. coli itself among bacteria recovered from the right wing — the real data is a net effect, not a clean disease/cure split.</div></details></div></div></div>",
      bullets: [
        { label: 'The Ḥadīth (Ṣaḥīḥ al-Bukhārī 3320)', text: '"إِذَا وَقَعَ الذُّبَابُ فِي شَرَابِ أَحَدِكُمْ فَلْيَغْمِسْهُ، ثُمَّ لِيَنْزِعْهُ، فَإِنَّ فِي إِحْدَى جَنَاحَيْهِ دَاءً وَالْأُخْرَى شِفَاءً" — "If a housefly falls in the drink of anyone of you, he should dip it in and then take it out, for one of its wings carries disease and the other carries the cure."' },
        { label: 'Macquarie University Research (2002)', text: 'Danny Kingsley, "The new buzz on antibiotics," ABC Science Online (1 Oct. 2002): a team led by PhD candidate Joanne Clarke, Dept. of Biological Sciences, Macquarie University, tested four fly species across their life stages against E. coli, Golden Staph, Candida, and a hospital pathogen. Antibacterial activity was found on the body surface (and in the gut) of larvae and adults in every case except the non-feeding pupal stage — "antibiotic action was observed every time." Presented at the Australian Society for Microbiology Conference, Melbourne.' },
        { label: 'The Direct Experimental Test — Claresta et al. (2020)', text: "\"The Right-Wing of Musca domestica as Neutralization of Drink Contamination,\" J. Nutr. Sci. Vitaminol. (Tokyo) 66(Supplement): S283-S285, Universitas Darussalam Gontor, Indonesia. E. coli-contaminated water treated with 1, 2, or 3 fly right-wings showed zero measurable microbial growth over 48 hours — statistically matching the sterile control — while the untreated contaminated water showed growth from the first 12 hours. Verbatim conclusion: \"it is proven that right-wing of Musca domestica fly can neutralize the drinks that have been contaminated by the Escherichia coli bacteria.\"" },
        { label: "A Broader Review of the Fly's Antimicrobial Arsenal", text: 'Niode et al. (2022) map five distinct antimicrobial-compound sources across the housefly\'s body: the digestive tract, the hemolymph, the cuticular lipid layer, whole-body extracts, and — specifically named as its own category — the right wing/body surface/entire body, which carries both bacteriophages and a family of antimicrobial peptides (mersacidin, subpeptin JM4-B, subtilosin A, sublancin, microcin L/J25, colicin, lactocylin O).' },
        { label: 'The Complicating Detail', text: "A separate wing-microbiome survey lists Escherichia coli itself among the bacterial genera recovered from the right wing, and finds Brucella melitensis and Sphingobacterium present on both wings. The clean claim \"one wing is pure disease, the other pure cure\" is a simplification of this real data; what the Claresta et al. experiment actually demonstrated was the right wing's net antibacterial effect in an applied test, not that the right wing is free of all pathogenic bacteria." },
      ],
      qanda: [
        { q: "What did Claresta et al.'s 2020 experiment actually measure, and what was its result?", a: "The study measured microbial growth in E. coli-contaminated water after adding 1, 2, or 3 fly right-wings, compared against a sterile positive control and an untreated contaminated negative control, using standard microbiological plating and colony counts over 48 hours at 37°C. The contaminated water with no wing added showed bacterial growth from the first 12 hours, while the water treated with the fly's right wing — at all three tested quantities — showed zero measurable growth, statistically matching the sterile control." },
        { q: "What specific complicating detail does this section flag about the \"one wing disease, other wing cure\" claim, and why does it matter?", a: "A separate wing-microbiome survey found that E. coli itself — the very pathogen the Claresta study tested against — is among the bacteria recovered from the right wing, and that some bacterial genera (Brucella melitensis, Sphingobacterium) appear on both wings rather than being cleanly separated. This matters because it shows the real underlying data is more complicated than a simple binary split; the actual experimental finding is about a net antibacterial effect the right wing produced in a specific applied test, not that the right wing carries zero pathogenic bacteria at all." },
        { q: 'What historical medical practice does the kaheel7.net material connect the fly ḥadīth to, and who are the specific researchers named?', a: "Maggot therapy — the deliberate use of fly larvae to clean wounds by consuming dead tissue while secreting antibacterial compounds. It cites Russian researcher Sergey Chernysh (St. Petersburg) documenting its use by surgeon Pirogov in the Crimean War and again in WWI, and German researchers Wim Fleischmann and Martin Auster's clinical work on larvae for wound healing, diabetes, bedsores, and bone infections, including a 3-year study at Bettelheim Hospital, Germany, and the Hohenstein Institute's development of maggot-derived wound dressings." },
      ],
      quiz: [
        { q: "What specific instruction does Ṣaḥīḥ al-Bukhārī 3320 give regarding a fly that falls into a drink?", choices: ['Dip the fly fully into the drink, then remove it', 'Leave the fly in the drink undisturbed', 'Boil the drink before removing the fly', 'Discard the drink immediately without touching the fly'], correct: 0 },
        { q: "What was the measured result of Claresta et al.'s 2020 experiment testing the fly's right wing against E. coli-contaminated water?", choices: ['The right wing had no measurable effect on bacterial growth', 'Water treated with 1, 2, or 3 right-wings showed zero measurable microbial growth, matching the sterile control', 'The right wing increased bacterial growth compared to the untreated water', 'The experiment was inconclusive due to equipment failure'], correct: 1 },
        { q: "What complicating detail does this section flag about the wing-microbiome data, regarding the specific bacterium E. coli?", choices: ["That E. coli is found exclusively on the left wing and never the right", "That E. coli has never been found on either wing of the fly", "That E. coli itself is listed among the bacterial genera recovered from the fly's right wing", "That E. coli was not involved in any of the studies discussed"], correct: 2 },
        { q: 'Which university team, presenting at the Australian Society for Microbiology Conference in 2002, tested antibacterial properties across four fly species and their life stages?', choices: ['A team at Thomas Jefferson University led by E. Marshall Johnson', 'A team at the University of Toronto led by Keith Moore', 'A team at Universitas Darussalam Gontor led by Ivena Claresta', 'A team at Macquarie University led by PhD candidate Joanne Clarke'], correct: 3 },
        { q: 'What historical wartime medical use of maggot therapy is cited via Russian researcher Sergey Chernysh?', choices: ["Its use by surgeon Pirogov in the Crimean War, and again in World War I", 'Its first recorded use during the fall of Constantinople', 'Its use exclusively in modern veterinary medicine, with no historical precedent', 'Its rejection by all military medical corps throughout history'], correct: 0 },
        { q: 'How does this section characterize the accurate takeaway from all the fly-related research combined, given the complicating wing-microbiome detail?', choices: ['That the fly ḥadīth has been definitively disproven by modern science', "That the right wing demonstrated a real, measured net antibacterial effect in applied testing, even though it is not simply free of all bacteria including pathogens", 'That flies carry no bacteria of any kind on either wing', 'That the research is entirely unrelated to the ḥadīth and should be disregarded'], correct: 1 },
      ]
    },
    {
      id: 'textual-unity', icon: '📊', label: "Is the Qurʾān Internally Consistent?", subtitle: 'Two Stylometric Studies, Read for What They Actually Claim', color: 'var(--emerald-light)',
      intro: "Two peer-reviewed papers apply computational stylometry to the Qurʾān. This section presents exactly what each paper claims — a finding about textual/stylistic unity and authorship-discrimination — without extending either claim further than its own authors state.<div class='xn-diagram-wrap'><div class='xn-diagram-title' style='color:var(--emerald-light)'>Two Papers, What They Actually Say (tap each one)</div><div class='xn-accordion'><details class='xn-acc-item'><summary><span>Sayoud (2015)</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>Clustering across 7 NLP features cleanly separates Quran text from Hadith text — 'a clear authorship distinction between the two religious books,' in the paper's own words.</div></details><details class='xn-acc-item'><summary><span>Sadeghi (2011)</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>Four independent style markers verify a 7-phase chronology and find stylistic unity across large passages — 'the Quran has one author,' per the abstract.</div></details><details class='xn-acc-item'><summary><span>What neither claims</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>Neither author frames the finding as evidence of divine origin — the claims are about authorship-discrimination and chronology, not theology.</div></details></div></div>",
      bullets: [
        { label: 'Sayoud (2015) — Qurʾān vs. Ḥadīth Clustering', text: 'Halim Sayoud, "A Visual Analytics based Investigation on the Authorship of the Holy Quran," Proceedings of the 6th International Conference on Information Visualization Theory and Applications (IVAPP 2015), pp. 177-181. Using Hierarchical Clustering and Fuzzy C-mean Clustering across seven types of NLP features (normalized via PCA), the study found two clearly separated clusters — one for Qurʾānic text, one for Ḥadīth text — with, in the paper\'s own words, "a clear authorship distinction between the two religious books."' },
        { label: 'Sadeghi (2011) — Stylometric Chronology', text: 'Behnam Sadeghi, "The Chronology of the Qurʾān: A Stylometric Research Program," Arabica 58 (2011): 210-299 (Brill). Verifies a seven-phase relative chronology using four independent style markers (average verse length, frequency profiles of 28 common morphemes, 114 other common morphemes, and 3,693 uncommon morphemes), each varying smoothly across the proposed phases. Verbatim from the abstract: "this essay demonstrates the stylistic unity of many large passages. It also shows that the Qurʾān has one author."' },
        { label: 'What These Papers Do NOT Claim', text: 'Neither paper is a theological argument, and neither author frames their finding as evidence of divine origin. Sayoud\'s stated purpose is authorship-discrimination between two specific text corpora; Sadeghi\'s stated purpose is verifying a proposed chronological ordering of the Qurʾān\'s composition. "One author" and "stylistic unity" in Sadeghi\'s abstract are claims about literary/compositional consistency, not a claim about who or what that one author was.' },
        { label: 'Why This Is Still Relevant to the Genre', text: "These findings are read in this literature as evidence against theories that the Qurʾān is a patchwork compiled by multiple later hands with inconsistent styles — since a genuinely disunified, multi-author patchwork text would be expected to show much greater stylistic variance across passages than either study actually found." },
      ],
      qanda: [
        { q: "What did Sayoud's 2015 clustering study actually measure, and what did it find?", a: "It measured seven types of natural-language-processing features across the Qurʾān and Ḥadīth corpora, reduced via principal component analysis, then applied two clustering methods (Hierarchical and Fuzzy C-mean). Both methods produced two clearly separated clusters corresponding exactly to the Qurʾān and the Ḥadīth respectively, which the paper itself describes as showing 'a clear authorship distinction between the two religious books' — i.e., a measurable, computable stylistic difference between the two corpora." },
        { q: "What does Sadeghi's abstract literally claim, and how should the phrase \"the Qurʾān has one author\" be understood?", a: "Sadeghi's abstract states the essay both verifies a seven-phase chronology using four independent style markers and demonstrates the stylistic unity of many large passages, concluding the Qurʾān has one author. This is a literary/compositional claim — about consistent authorial style across the text, as measured by verse-length and morpheme-frequency patterns — not a claim Sadeghi himself frames as proof of supernatural or divine origin; the paper does not argue that point at all." },
        { q: 'Why does this section explicitly caution against extending these two papers\' findings further than their own authors state?', a: "Because doing so would misrepresent what the papers actually argue: Sayoud's paper is about authorship-discrimination methodology between two specific corpora, and Sadeghi's is about verifying a proposed compositional chronology. Treating either as an independent scientific proof of divine authorship would be reading into them a claim their own authors never make, which conflicts with this book's stated commitment to citing sources for exactly what they say." },
      ],
      quiz: [
        { q: 'What two clustering methods does Sayoud (2015) use to analyze the Qurʾān and Ḥadīth corpora?', choices: ['Only manual expert review with no computational method', 'A single neural network with no clustering technique', 'Hierarchical Clustering and Fuzzy C-mean Clustering', 'Random sampling with no statistical method at all'], correct: 2 },
        { q: 'What specific conclusion does Sayoud\'s paper state, in its own words, about the Qurʾān and Ḥadīth corpora?', choices: ['That the two corpora are stylistically identical with no distinguishable difference', 'That neither corpus can be analyzed using NLP methods at all', 'That the Ḥadīth corpus is older than the Qurʾān corpus', 'That there is "a clear authorship distinction between the two religious books"'], correct: 3 },
        { q: 'What four independent style markers does Sadeghi (2011) use to verify a seven-phase chronology of the Qurʾān?', choices: ["Average verse length, and frequency profiles of 28, 114, and 3,693 morphemes", 'Only the total word count of each sūrah', 'The number of times each Prophet is mentioned by name', 'The physical ink color used in early manuscripts'], correct: 0 },
        { q: 'What does Sadeghi\'s abstract literally state about the Qurʾān\'s authorship, in his own words?', choices: ['That it was compiled by multiple authors across several centuries', 'That "it also shows that the Qurʾān has one author"', 'That authorship cannot be determined by any stylometric method', 'That the Qurʾān\'s authorship is identical to that of pre-Islamic Arabic poetry'], correct: 1 },
        { q: 'Why does this section explicitly state that neither Sayoud nor Sadeghi frames their finding as proof of divine origin?', choices: ['Because both authors explicitly deny the Qurʾān has any historical value', 'Because both papers were later retracted by their respective journals', 'Because their stated purposes are authorship-discrimination and chronological verification respectively, and extending their findings further would misrepresent what they actually argue', 'Because stylometry is considered an invalid method by all linguists'], correct: 2 },
        { q: 'According to this section, why are these two stylometric findings still considered relevant to the broader Iʿjāz ʿIlmī literature, despite not being theological arguments?', choices: ['Because they focus exclusively on the meaning of individual verses rather than style', 'Because they mathematically prove the Qurʾān was revealed rather than written', 'Because they were commissioned directly by Islamic religious authorities', 'Because they are read as evidence against theories of the Qurʾān as a multi-author patchwork, since such a text would show far greater stylistic variance than was actually found'], correct: 3 },
      ]
    },
  ]
});
