/* XENOS NOTES — book module
 * To add a new book: copy this file's shape, fill in the metadata + sections, save
 * it as books/<your-slug>.js, then add one <script> line in index.html. That's it —
 * the shared engine (app.js) handles rendering, navigation, search, and styling. */
XenosBooks.register({
  slug: 'mantiq-bayan',
  title: 'Manṭiq & Bayān',
  subtitle: 'Where a Modern Logic Textbook and Classical Islamic Reasoning Meet',
  icon: '🧩',
  category: 'Manṭiq',
  arabicBg: 'المنطق والبيان',
  tags: ['Manṭiq', 'Uṣūl al-Fiqh', 'Kalām', 'Language & Logic'],
  footer: 'Built around concepts from Logic Made Easy: How to Know When Language Deceives You by Deborah J. Bennett (W.W. Norton, 2004), paired with the parallel Islamic intellectual tradition — kalām, uṣūl al-fiqh, and the classical Muslim debate over Aristotelian logic itself',

  sections: [
    {
      id: 'proof-and-contradiction', icon: '🪞', label: 'Proof, Contradiction, and Q21:22', subtitle: 'A Logical Law the Qurʾān Itself Argues From', color: 'var(--burgundy)',
      intro: 'Deborah J. Bennett\'s Logic Made Easy opens with two of Aristotle\'s founding axioms: the law of the excluded middle (a thing either has a given attribute or does not — there is no third option) and the law of noncontradiction (a thing cannot both have and not have that attribute at the same time). These aren\'t just Greek philosophy — a version of the same reasoning move, reductio ad absurdum ("proof by contradiction": assume the opposite of what you want to prove, show it leads to an impossible result, conclude your original claim is true), is used directly in the Qurʾān to argue for tawḥīd, and was later formalized by Muslim theologians as a named proof.',
      bullets: [
        { label: "Bennett's law of noncontradiction", text: 'A thing cannot both be and not be at the same time — a shape cannot be both a circle and not a circle. Aristotle repeatedly justified logical claims by appeal to the impossibility of a thing "both is and is not at the same time." Proof by contradiction (reductio ad absurdum) works by assuming a claim\'s opposite, deriving something impossible from it, and concluding the original claim must be true — used throughout mathematics from antiquity onward.' },
        { label: 'Q21:22 — burhān at-tamānuʿ, "the proof from mutual hindrance"', text: '"Had there been within the heavens and earth gods besides Allah, they both would have been ruined. So exalted is Allah, Lord of the Throne, above what they describe" (Al-Anbiyāʾ). Classical mutakallimūn (scholastic theologians) read this as a formal proof by contradiction: assume more than one all-powerful god exists; if they ever disagreed, either both wills prevail (impossible — a single event cannot have two full causes) or one is overridden (meaning the overridden one was never truly all-powerful, contradicting the assumption). Either branch collapses into an impossibility, so the original assumption — more than one god — is false.' },
        { label: "This is a named proof in classical kalām", text: 'Ashʿarī and Māturīdī theological manuals treat burhān at-tamānuʿ as a standard, citable argument for tawḥīd, not an incidental turn of phrase — it appears in works of ʿilm al-kalām specifically because its logical structure (a clean reductio ad absurdum) was recognized and valued as such, independently of and prior to any direct borrowing from Aristotle.' },
        { label: "Al-Ghazālī's case that logic itself is neutral — Miʿyār al-ʿIlm, Miḥakk an-Naẓar", text: 'Al-Ghazālī argued that the tools of logic (definition, syllogism, the very laws Bennett opens her book with) are religiously neutral instruments, no more "Greek" or "un-Islamic" than arithmetic — what matters is whether the premises fed into them are true, and whether the philosophers\' metaphysical conclusions actually followed validly from sound premises. He used this to attack the philosophers (in Tahāfut al-Falāsifah) on their own logical terms, showing several of their signature conclusions did not actually follow by the very rules of inference they claimed to honour.' },
        { label: "Ibn Taymiyyah's counter-case — Kitāb ar-Radd ʿalā al-Manṭiqiyyīn", text: 'A very different and much more skeptical position: Ibn Taymiyyah argued Aristotelian categorical logic, especially the syllogism, was neither necessary nor sufficient for sound reasoning — that ordinary human fiṭrah (innate reasoning capacity) and the Qurʾān\'s own argumentative style (direct address, concrete example, analogy) reach truth more reliably than the formal machinery of the logicians, which he considered prone to smuggling in unexamined and sometimes false premises behind a screen of technical rigor.' },
        { label: "Two Muslim scholars, one Greek toolkit, opposite verdicts", text: 'Al-Ghazālī: logic is a neutral tool worth mastering to defeat bad philosophy on its own ground. Ibn Taymiyyah: the tool itself is oversold, and the Qurʾān\'s own mode of argument is both older and more trustworthy. Bennett\'s book, arguing that formal logic still trips up modern readers eight centuries later, is closer in spirit to a third position — that the tool is useful precisely because ordinary reasoning is less reliable than people assume, which is closer to al-Ghazālī\'s instinct than Ibn Taymiyyah\'s.' },
      ],
      qanda: [
        { q: 'How does Q21:22 function as a formal proof by contradiction, step by step?', a: 'It assumes the opposite of tawḥīd (more than one all-powerful god), shows that assumption forces an impossible situation (two full, unopposed wills governing the same event, or one god secretly not being all-powerful after all), and concludes the original assumption must be false — exactly Aristotle\'s reductio structure, applied to theology rather than geometry.' },
        { q: "Why does it matter that Ashʿarī and Māturīdī kalām manuals gave this argument a name (burhān at-tamānuʿ) rather than treating it as incidental phrasing?", a: "Naming and citing a proof as a proof shows the classical mutakallimūn recognized its logical structure as reusable and rigorous — they were doing formal argumentation, not merely rhetorical flourish, and this particular move became a standard citable tool in later kalām works on tawḥīd." },
        { q: "What is the actual disagreement between al-Ghazālī and Ibn Taymiyyah on logic, and what do they agree on?", a: "They disagree on whether Aristotelian logic is a useful, neutral tool (al-Ghazālī) or an oversold, premise-smuggling one that adds little beyond fiṭrah and the Qurʾān's own style (Ibn Taymiyyah). They agree on the underlying goal — sound reasoning in defense of correct belief — and neither rejects logic in the loose sense of 'valid inference,' only its formal Aristotelian packaging as uniquely necessary." },
      ],
    },
    {
      id: 'all-and-some', icon: '🧮', label: "All, Some, and 'Āmm vs. Khāṣṣ", subtitle: 'The Discipline of Precise Quantifiers, in English and in Fiqh', color: 'var(--emerald)',
      intro: 'Bennett devotes a full chapter to how often people misuse "all," "some," "none," and "every" — English quantifiers that look simple but aren\'t. She shows that "all" statements are disproven by a single counterexample, that "some" doesn\'t tell you how many, and that people regularly confuse contradictories (statements that can\'t both be true and can\'t both be false) with contraries (statements that can both be false). Uṣūl al-fiqh — the discipline governing how scholars correctly derive rulings from the Qurʾān and Sunnah — has its own, older vocabulary for exactly this same precision problem.',
      bullets: [
        { label: "Bennett's quantifiers: all/every vs. some/many/few", text: '"All" and "every" are universal quantifiers — 100% of a category, disproven by one counterexample. "Some," "many," and "few" are vague partial quantifiers; "some" in strict logic just means "at least one," not "most" or "a lot," which is routinely misread in ordinary conversation.' },
        { label: 'ʿĀmm (عَامّ) — the general/universal term in uṣūl al-fiqh', text: 'A wording that, by its Arabic construction, covers every individual member of a category without exception unless a specific piece of evidence (mukhaṣṣiṣ) restricts it — functioning exactly like Bennett\'s universal quantifier, but as a technical category scholars must identify correctly before deriving a ruling from a text.' },
        { label: 'Khāṣṣ (خَاصّ) — the particular/restricted term', text: "A wording that applies only to a specific, identified individual or a limited subset — Bennett's particular statement. The practical stakes in fiqh are high: mistaking an ʿāmm ruling for one that was actually always khāṣṣ (or vice versa) changes who the ruling actually binds." },
        { label: "Takhṣīṣ — restricting an apparently general text", text: "Scholars distinguish a text that is genuinely universal from one that looks universal in isolation but is restricted (mukhaṣṣaṣ) by another verse, hadith, or scholarly consensus — the same discipline Bennett is teaching when she insists a reader check whether \"all\" really means all before accepting a conclusion built on it." },
        { label: "Bennett's contradictories vs. contraries — and the fiqh parallel", text: '"All people are rich" and "No people are rich" are contraries — both can be false at once (some rich, some not). "All people are rich" and "Some people are not rich" are contradictories — exactly one must be true. Conflating the two is a named error in both traditions: getting this wrong in fiqh can make a scholar think a ruling has been overturned by a text that only ever qualified it.' },
        { label: 'A concrete worked example', text: 'Q4:23 lists specific women forbidden in marriage (khāṣṣ — a bounded, named list) versus the general statement in Q4:24 that "lawful to you are [all others] beyond those mentioned" (ʿāmm, restricted by the khāṣṣ list before it). Reading Q4:24 as a free-standing universal — the way Bennett\'s "all New Jersey residents must fill out Form 203" trap catches income-tax readers — without checking what restricts it would misstate the actual ruling.' },
      ],
      qanda: [
        { q: "Why does Bennett say a single counterexample can disprove an 'all' claim, but not the reverse (a single example can't prove an 'all' claim)?", a: "Because 'all S are P' is a claim about every member of S with no exceptions — one confirmed exception (an S that is not P) breaks that claim entirely, but any number of confirming examples still leaves open the possibility of an exception you haven't checked yet, so they can never add up to certainty the way one counterexample delivers certain disproof." },
        { q: "What is the practical risk of confusing an ʿāmm (general) text with a khāṣṣ (particular) one in deriving a fiqh ruling?", a: "Treating a genuinely restricted ruling as if it applied universally (or vice versa) misstates who or what the ruling actually covers — exactly the same category of error Bennett documents with 'all New Jersey residents' vs. 'only New Jersey residents,' just with real legal consequences in fiqh rather than a tax form." },
        { q: 'How does the contradictory/contrary distinction help a reader avoid overreading a restricting (khāṣṣ) text as though it cancelled a general (ʿāmm) one entirely?', a: "A khāṣṣ text that restricts an ʿāmm one is usually working as a contrary-style qualification (narrowing the general claim in specific cases) rather than a contradictory (flatly negating it) — recognizing which relationship is actually in play prevents concluding the general ruling was overturned when it was only ever qualified." },
      ],
    },
    {
      id: 'conditionals-mafhum', icon: '🔀', label: 'If/Then, and Mafhūm al-Mukhālafah', subtitle: 'The Same Mistake, Twice: Reading a Conditional as Its Converse', color: 'var(--gold)',
      intro: 'One of Bennett\'s central findings, backed by decades of cognitive-psychology research, is that people overwhelmingly misread "if P then Q" as also meaning "if not-P then not-Q" — treating a one-directional conditional as if it were a two-directional biconditional. Classical uṣūl al-fiqh built an entire, centuries-long debate around exactly this move, under the name mafhūm al-mukhālafah (the "divergent implication," also called dalīl al-khiṭāb) — and scholars split badly over whether it is ever a valid way to extract a ruling.',
      bullets: [
        { label: "Bennett: the conditional/biconditional confusion", text: 'Given "if it rains, she will spoil her shoes," people commonly and wrongly infer "if it does not rain, she will not spoil her shoes" — treating a one-way implication as if it worked both ways. Research cited in Logic Made Easy found this error is dramatically reduced (from roughly 25% correct to 70–100% correct, depending on age group) simply by making the necessity of the connection explicit in the wording — showing this is a real, measurable, widespread pattern, not a rare slip.' },
        { label: 'Mafhūm al-mukhālafah (مفهوم المخالفة) — the same move, named centuries earlier', text: 'When a ruling is stated with an explicit restriction or condition — a number, a description, a named exception — some uṣūl scholars hold that the opposite of the ruling applies when that condition is absent. Example type: "for grazing livestock, there is zakāh" is read by some scholars as implying "for non-grazing (stall-fed) livestock, there is no zakāh" — inferring the converse from the stated condition.' },
        { label: 'A genuine, centuries-old scholarly split', text: 'Ḥanafī uṣūlīs are broadly the most skeptical of treating mafhūm al-mukhālafah as binding proof on its own, worried it over-infers from silence. Shāfiʿī and Ḥanbalī uṣūlīs more readily accept it in specific sub-forms (mafhūm ash-sharṭ for conditional statements, mafhūm al-waṣf for descriptive qualifiers, mafhūm al-ʿadad for stated numbers) while still debating which sub-forms are strong enough to build a ruling on. This is not a fringe dispute — it is a standard, named fault-line covered in every major uṣūl al-fiqh textbook.' },
        { label: 'Why the disagreement matters, in Bennett\'s own terms', text: 'Bennett shows the conditional/biconditional slide is a natural, near-universal tendency of human reasoning — not a mark of carelessness alone. Reading the uṣūl al-fiqh debate against that backdrop reframes it: the Ḥanafī caution against mafhūm al-mukhālafah can be read as a formal safeguard against exactly the cognitive bias Bennett\'s cognitive-psychology sources document, built into the discipline centuries before anyone ran a controlled experiment on it.' },
        { label: "Bennett's causation warning, and istidlāl bi-l-ʿillah", text: 'Bennett separately warns that people tend to read a conditional\'s antecedent as the unique cause of its consequent ("if it rains, she\'ll spoil her shoes" gets read as "only rain could spoil her shoes"). Uṣūl al-fiqh\'s own emphasis on correctly identifying the ʿillah (underlying effective cause) behind a ruling — rather than assuming the stated condition is the only possible trigger — targets the same reasoning failure from the legal-reasoning side.' },
      ],
      qanda: [
        { q: "In Bennett's terms, what exactly is the logical move scholars are debating when they discuss mafhūm al-mukhālafah?", a: "Whether it's valid to read a stated conditional ruling ('if P, then Q') as also implying its converse ('if not-P, then not-Q') — precisely the conditional-to-biconditional inference Bennett's chapter on conditionals documents as a widespread, well-studied human reasoning error, except uṣūl al-fiqh treats it as a live methodological question rather than simply a mistake to avoid." },
        { q: 'Why are Ḥanafī scholars generally more cautious about mafhūm al-mukhālafah than Shāfiʿī or Ḥanbalī scholars?', a: "Because inferring the converse of a stated ruling risks manufacturing a rule the text never actually stated, based only on what it didn't say — the Ḥanafī caution treats silence about the opposite case as genuinely uninformative by default, rather than as an implied ruling, which functions as a safeguard against over-reading conditionals exactly as Bennett's research describes." },
        { q: "How does Bennett's finding that making a conditional's necessity explicit sharply improves accuracy relate to how uṣūl al-fiqh handles ambiguous conditional rulings?", a: "Both traditions converge on the same fix: precision in how a condition is worded (or classified) determines whether the converse can be safely inferred — uṣūl al-fiqh's sub-categories (mafhūm ash-sharṭ, mafhūm al-waṣf, mafhūm al-ʿadad) exist specifically to sort stronger from weaker cases for this same reason." },
      ],
    },
    {
      id: 'two-kinds-of-qiyas', icon: '⚖️', label: 'Two Kinds of Analogy: Manṭiqī and Fiqhī', subtitle: "Ibn Taymiyyah's Argument That the Jurists Had It Right All Along", color: 'var(--burgundy-deep)',
      intro: "Bennett's chapters on syllogisms cover Aristotle's qiyās manṭiqī — categorical deduction from two premises sharing a middle term (\"all A is B; all B is C; therefore all A is C\"), the ruleset later formalized with Venn diagrams and truth tables. Islamic legal theory has its own qiyās (قياس) — usually translated \"analogy\" — but it is a structurally different kind of reasoning, and one of the most striking claims in Ibn Taymiyyah's critique of the logicians is that this fiqhī version is the more reliable of the two for reasoning about the real world.<div class='xn-diagram-wrap'><div class='xn-diagram-title' style='color:var(--burgundy-deep)'>Interactive — The Four Pillars of Qiyās Fiqhī (tap to expand)</div><div class='xn-accordion'><details class='xn-acc-item'><summary><span>1. Al-Aṣl — the source case</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>The original case with a known, textually-established ruling. Example: grape wine (khamr), explicitly prohibited by nāṣṣ (Q5:90).</div></details><details class='xn-acc-item'><summary><span>2. Al-Farʿ — the new case</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>The new, unaddressed case a scholar wants to rule on. Example: a modern distilled spirit, never mentioned by name in the primary texts.</div></details><details class='xn-acc-item'><summary><span>3. Al-ʿIllah — the shared effective cause</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>The underlying reason the source ruling exists — for khamr, scholars identify this as intoxication (iskār), not \"grape-ness.\" Finding the correct ʿillah, rather than a superficial resemblance, is the most contested and skill-dependent step in the whole method.</div></details><details class='xn-acc-item'><summary><span>4. Al-Ḥukm — the transferred ruling</span><span class='xn-acc-marker'>+</span></summary><div class='xn-acc-body'>Once the ʿillah is confirmed present in the new case, the source ruling transfers to it — the distilled spirit is ruled prohibited, not because it resembles wine, but because it shares wine's actual reason for prohibition.</div></details></div></div>",
      bullets: [
        { label: "Qiyās manṭiqī — Aristotle's categorical syllogism", text: 'Two premises sharing a "middle term" force a conclusion by the sheer form of the argument: "all A is B; all B is C; therefore all A is C" is valid regardless of what A, B, and C actually stand for. Its power is that the form alone guarantees validity — but, as Bennett\'s chapter shows at length, humans are bad at applying that form correctly under real-world conditions (the "atmosphere effect," where the mood of the premises biases which conclusion feels right regardless of actual validity).' },
        { label: "Qiyās fiqhī — juristic analogy", text: 'Reasoning from a case with a known textual ruling (al-aṣl) to a new, unaddressed case (al-farʿ) on the basis of a shared underlying cause (al-ʿillah) — see the interactive breakdown above. Its power is different from a syllogism\'s: it extends real, textually-grounded rulings to genuinely new situations the primary texts never explicitly named, which categorical logic alone cannot do, since a syllogism can only make explicit what its premises already contained.' },
        { label: "Ibn Taymiyyah's argument, condensed", text: 'In Kitāb ar-Radd ʿalā al-Manṭiqiyyīn, Ibn Taymiyyah argues the fuqahāʾ\'s qiyās, built on identifying a genuine shared ʿillah between two real cases, is epistemically stronger for reasoning about the world than an Aristotelian syllogism, because the syllogism\'s "all A is B" universal premise is itself usually established by exactly the kind of inductive, case-based reasoning the jurists were already doing — meaning the syllogism doesn\'t actually add certainty so much as dress up conclusions that were reached some other way.' },
        { label: 'Where the two methods can go wrong, compared', text: 'A syllogism fails when a premise is false, even if the logical form is perfectly valid (Bennett\'s "all tornadoes are destructive" example). A juristic analogy fails when the proposed ʿillah is wrong — mistaking a superficial resemblance (colour, origin, name) for the actual operative reason behind a ruling is the single most common documented error in classical qiyās criticism literature, and is functionally the same failure mode as Bennett\'s warning against assuming a stated cause is the only possible cause.' },
        { label: "A worked example of qiyās fiqhī", text: "Al-aṣl: grape wine (khamr), prohibited by Q5:90. Al-farʿ: a modern distilled spirit not named in the primary texts. Al-ʿillah: intoxication (iskār) — identified, not assumed, as the actual reason wine is prohibited, distinguishing it from irrelevant features like being made from grapes specifically. Al-ḥukm: since the new spirit shares the ʿillah of intoxication, the same prohibition transfers to it — a conclusion no categorical syllogism could reach on its own, since none of its premises could mention a substance invented centuries after the ruling was revealed." },
      ],
      qanda: [
        { q: "What is the core structural difference between qiyās manṭiqī and qiyās fiqhī, in plain terms?", a: "Qiyās manṭiqī derives a conclusion that was already logically contained in its premises — it makes the implicit explicit, but adds no new information. Qiyās fiqhī extends a known ruling to a genuinely new case by identifying a shared underlying cause (ʿillah), which is how it can address situations the original texts never named." },
        { q: "According to Ibn Taymiyyah's critique, why doesn't the Aristotelian syllogism actually deliver the certainty it claims to?", a: "Because its universal premises ('all A is B') are themselves usually established through the same inductive, case-based reasoning the jurists already use — the syllogism doesn't independently verify those premises, it just re-packages a conclusion already reached by other means, so its added certainty is more apparent than real." },
        { q: 'In the qiyās fiqhī worked example, why is identifying the correct ʿillah described as the most contested step, rather than the transfer of the ruling itself (al-ḥukm)?', a: "Because once a shared ʿillah is genuinely established, the ruling transfers almost automatically — the real scholarly work and the real risk of error both lie in correctly isolating what actually causes the original ruling (intoxication, not grape origin), since mistaking a superficial resemblance for the true ʿillah produces a confidently wrong analogy." },
      ],
    },
    {
      id: 'fallacies-and-adab-al-jadal', icon: '🎭', label: 'Fallacies, Sophists, and Adab al-Jadal', subtitle: 'Winning an Argument vs. Being Right', color: 'var(--emerald-light)',
      intro: 'Bennett traces the origin of formal logic partly to Plato and Aristotle\'s irritation with the Sophists — professional arguers who used "deliberate confusion and verbal tricks" to win debates regardless of truth. Islamic scholarship developed its own extensive literature on the ethics and technique of disputation (jadal, munāẓarah), explicitly distinguishing argument aimed at reaching truth from argument aimed merely at defeating an opponent — the same distinction, arrived at independently, that motivated Aristotle to formalize logic in the first place.',
      bullets: [
        { label: "Bennett on the Sophists and the false dilemma", text: 'The "false dilemma" or misused excluded middle — presenting only two options when a third exists ("either you\'re with me or against me") — is, per Bennett, exactly the kind of verbal maneuvering Plato and Aristotle attacked in the Sophists (citing Plato\'s Euthydemus, where a young man is trapped into agreeing he is either "wise or ignorant," with no room allowed for a middle position). Bennett notes this same move remains common in modern political rhetoric.' },
        { label: 'Al-jadal and munāẓarah — the classical Islamic disputation tradition', text: 'A developed genre of scholarly literature (works like al-Jadal by Ibn ʿAqīl, and later systematic ādāb al-baḥth wa-l-munāẓarah manuals) laying out rules for formal scholarly debate — how to state a claim, how to demand and evaluate evidence, and what counts as an illegitimate rhetorical move rather than genuine argument.' },
        { label: "The Qurʾān's own standard for how to argue — Q29:46, Q16:125", text: '"Argue not with the People of the Scripture unless it be in a way that is better" (Q29:46). "Invite to the way of your Lord with wisdom and good instruction, and argue with them in a way that is best" (Q16:125). These verses set a standard — better manner, not just correct logical form — that goes beyond what Aristotle\'s Organon addresses; validity and courtesy are treated as separate, both-required conditions for a good argument.' },
        { label: "Equivocation, in both traditions", text: 'Bennett covers equivocation — sliding between two different meanings of the same word mid-argument — as a classic fallacy. Uṣūl al-fiqh has its own sustained concern with exactly this failure mode in a specifically textual form: mushtarak (a term with multiple possible meanings in the sacred texts) must be disambiguated by context before a ruling can be safely derived from it, since deriving two different rulings by silently switching between a word\'s senses produces exactly Bennett\'s equivocation fallacy, with legal consequences attached.' },
        { label: 'Winning vs. being right — a shared ethical line', text: 'Bennett quotes Lewis Carroll on the appeal of mastering symbolic logic: it lets you "detect fallacies" and "tear to pieces the flimsy illogical arguments" you meet "in books, in newspapers, in speeches, and even in sermons." The classical adab al-jadal literature adds an explicit ethical rule Carroll doesn\'t: that the purpose of disputation is properly to arrive at truth together, not merely to defeat an opponent — a distinction this collection\'s own "Family Dialogue & Communication" section (see the Aqwāl book) makes independently about ordinary household disagreement.' },
      ],
      qanda: [
        { q: "How does Bennett's account of the Sophists connect to the false-dilemma fallacy specifically?", a: "The Sophists' verbal tricks, as Bennett describes them via Plato's Euthydemus, frequently took the form of forcing an opponent into an artificial two-option choice when a genuine third option existed — misapplying the law of the excluded middle (which only legitimately applies when there truly is no middle ground) as a rhetorical weapon rather than a logical law." },
        { q: 'What is the mushtarak problem in uṣūl al-fiqh, and how does it map onto Bennett\'s "equivocation" fallacy?', a: "Mushtarak is a term that legitimately carries more than one meaning in Arabic and in the sacred texts; a ruling derived by silently switching between those meanings mid-argument commits the same structural error as Bennett's equivocation fallacy — using one word to smuggle in two different claims without acknowledging the shift." },
        { q: "What does the adab al-jadal tradition add to the standard Bennett and Lewis Carroll set for a 'good' argument, that pure logical validity alone doesn't cover?", a: "An explicit ethical standard for manner and purpose — Q16:125 and Q29:46 require arguing 'in a way that is best,' and classical disputation manuals treat the goal of arguing well as reaching truth jointly, not simply defeating an opponent, adding a dimension (courtesy, shared purpose) that formal validity checks alone are silent on." },
      ],
    },
    {
      id: 'quizzes', icon: '🧠', label: 'Quizzes', subtitle: 'All Thirty Questions From the Sections Above, in One Place', color: 'var(--gold)',
      intro: 'Every quiz question from the five sections above, pooled here in one combined quiz, in the same order as the sections themselves.',
      quiz: [
        { q: 'What two things does a valid proof by contradiction (reductio ad absurdum) require, according to Bennett?', choices: ['Assuming the opposite of the claim, then showing that assumption leads to an impossibility', 'A famous author and a long history', 'A visual diagram and a truth table', 'Agreement from at least two independent scholars'], correct: 0 },
        { q: 'What is the core logical structure of Q21:22\'s argument against multiple gods (burhān at-tamānuʿ)?', choices: ['An appeal to majority scholarly opinion', 'Assuming multiple all-powerful gods, showing this leads to an impossible situation, and concluding tawḥīd is true', 'A direct command with no supporting reasoning', 'A comparison to pre-Islamic Arab poetry'], correct: 1 },
        { q: "What is the central disagreement between al-Ghazālī and Ibn Taymiyyah regarding Aristotelian logic?", choices: ['Whether logic exists at all', 'Whether the Qurʾān contains any arguments', "Al-Ghazālī saw it as a neutral, useful tool; Ibn Taymiyyah saw it as oversold compared to fiṭrah and the Qurʾān's own argumentative style", 'Whether Greek philosophy should be translated into Arabic'], correct: 2 },
        { q: 'According to Bennett, how many counterexamples does it take to disprove an "all" statement?', choices: ['At least three', 'A majority of cases', 'It can never be fully disproven', 'Just one'], correct: 3 },
        { q: 'What does ʿāmm mean in uṣūl al-fiqh, and what is its rough logical equivalent in Bennett\'s vocabulary?', choices: ['A general, universal term; equivalent to "all/every"', 'A restricted, particular term; equivalent to "some"', 'A metaphorical term with no literal meaning', 'A term found only in poetry, never in legal texts'], correct: 0 },
        { q: 'What is the difference between "contradictory" and "contrary" statement pairs, as Bennett defines them?', choices: ['There is no real difference between them', 'Contraries can both be false at once; contradictories cannot — exactly one of a contradictory pair must be true', 'Contradictories can both be false at once; contraries cannot', 'Both terms only apply to mathematical statements'], correct: 1 },
        { q: 'What reasoning error does Bennett identify as extremely common when people interpret an "if P then Q" conditional statement?', choices: ['Ignoring the statement entirely', 'Assuming P and Q are unrelated', 'Reading it as also meaning its converse, "if not-P then not-Q" (treating it as a biconditional)', 'Assuming the statement is always false'], correct: 2 },
        { q: 'What is mafhūm al-mukhālafah in uṣūl al-fiqh?', choices: ['A rule about how to pray correctly', 'A term for weak, unreliable hadith narrators', 'A category of permissible business transactions', 'The idea that the converse of a stated conditional ruling may also be implied by the text'], correct: 3 },
        { q: 'Which school of Islamic legal theory is generally described as most cautious about accepting mafhūm al-mukhālafah as valid proof?', choices: ['Ḥanafī', 'Shāfiʿī', 'Ḥanbalī', 'None of the schools ever discussed it'], correct: 0 },
        { q: 'According to Bennett\'s cited research, what happened to accuracy rates when a conditional\'s necessity was made explicit in the wording?', choices: ['Accuracy decreased significantly', 'Accuracy improved dramatically for both children and adults', 'There was no measurable change', 'Only adults improved; children showed no change'], correct: 1 },
        { q: 'What is the key structural difference between qiyās manṭiqī (Aristotelian syllogism) and qiyās fiqhī (juristic analogy)?', choices: ['They are identical in every respect', 'Qiyās fiqhī is only used in mathematics', 'Qiyās manṭiqī makes explicit what premises already contain; qiyās fiqhī extends a known ruling to a new case via a shared ʿillah', 'Qiyās manṭiqī was invented by Muslim scholars first'], correct: 2 },
        { q: 'In the four pillars of qiyās fiqhī, what does al-ʿillah refer to?', choices: ['The new, unaddressed case', 'The original case with a known ruling', 'The scholar who first proposed the analogy', 'The underlying effective cause shared between the two cases'], correct: 3 },
        { q: "According to Ibn Taymiyyah's critique, why doesn't the Aristotelian syllogism deliver the independent certainty it claims to?", choices: ['Because its universal premises are themselves usually established by the same inductive reasoning jurists already use', 'Because syllogisms are always invalid', 'Because Aristotle never actually wrote about syllogisms', 'Because syllogisms only work in Greek, not Arabic'], correct: 0 },
        { q: 'In the worked qiyās example about a modern distilled spirit, what is identified as the ʿillah (shared cause) linking it to the prohibition of wine?', choices: ['Being made from grapes', 'Intoxication (iskār)', 'Its country of origin', 'Its price'], correct: 1 },
        { q: "Which Qurʾānic verses does this section cite as setting a standard for HOW to argue, beyond mere logical validity?", choices: ['Q2:255 and Q112:1', 'Q1:1 and Q1:7', 'Q29:46 and Q16:125', 'Q4:34 and Q2:228'], correct: 2 },
        { q: 'What is the mushtarak problem in uṣūl al-fiqh, and which of Bennett\'s fallacies does it parallel?', choices: ['A rule about who can lead prayer — no logical parallel', 'A dispute about calendar dates — paralleling the false dilemma', 'A financial term — paralleling circular reasoning', 'A term with multiple possible meanings whose senses get silently swapped mid-argument — paralleling equivocation'], correct: 3 },
      ],
    },
  ]
});
