/* XENOS NOTES — book module
 * Sourced from How to Be a Real Man, AMAU Academy course notes (24 chapters,
 * compiled by the AMAU Admin team — the source itself notes these notes have
 * not been comprehensively checked by a teacher, and a couple of the hadith
 * it cites are themselves flagged in the source as carrying some weakness;
 * both are preserved honestly below rather than smoothed over). */
XenosBooks.register({
  slug: 'real-man',
  title: 'How to Be a Real Man',
  subtitle: '24 Chapters on the Islamic Balance of Masculinity — Strength Paired With Gentleness',
  icon: '⚔️',
  category: 'Love & Family',
  arabicBg: 'رجولة',
  tags: ['Manhood', 'Character', 'Adab', 'Men'],
  footer: 'Sourced from How to Be a Real Man, AMAU Academy course notes — 24 chapters on the Islamic balance of masculinity.',

  sections: [
    {
      id: 'foundations', icon: '🕌', label: 'Foundations', subtitle: 'Chapters 1–4 · Why Manhood Needs Defining, and What Anchors It', color: 'var(--burgundy)',
      intro: "The course opens by naming why this topic needs its own treatment at all: masculinity today is pulled toward two extremes at once — a culture that treats it as something to be erased, and a hyper-masculine gang/pornography culture that treats it as raw dominance — while family breakdown means many young men have no father figure passing manners down at all. Islam's answer isn't a new set of virtues invented for men, but the same character the Qur'an and Sunnah ask of everyone, examined specifically through how a man lives it out. The first four chapters lay the foundation everything else builds on: religion first, then determination balanced by reliance on Allah, then independence of judgment.",
      bullets: [
        { label: 'Why this needs saying at all — the two extremes', text: "The course names five causes for today's crisis in masculinity: an ideological war that treats masculinity itself as something negative; a hyper-masculine counter-culture (gang culture, pornography, 'macho' film characters) that fuels the same cycle from the other side; family breakdown leaving many boys with no father figure — not only through divorce, but through fathers too busy to give tarbiyah, outsourced instead to a screen; the loss of even the pre-Islamic Arab culture's own inherited manners, which Islam refined rather than replaced; and a general loss of religious knowledge, including the old model of learning adab directly from a teacher's own example. Imam Mālik's mother told him: \"Go to Rabīʿah and learn from his etiquette before you learn from his knowledge.\"" },
        { label: "Manners before difference — Ṣaḥīḥ Muslim, Sunan Abī Dāwūd", text: 'Two hadith frame the whole course: "I was only sent to perfect noble character" (narrated in Musnad Aḥmad, with al-Bazzār\'s wording "righteous manners"), and ʿĀʾishah\'s report that "women are nothing but the full sisters of men" (Sunan Abī Dāwūd). The point: this course isn\'t describing a separate moral code for men, only asking how the same Qur\'anic character looks when a man specifically embodies it — since, per Q49:13, "the most noble of you in the sight of Allah is the most righteous of you," regardless of sex.' },
        { label: "Nothing takes a real man from his religion — Q24:37, Ṣaḥīḥ al-Bukhārī", text: 'Q24:37 describes "men whom neither commerce nor sale distracts from the remembrance of Allah" — not men without desire (Q3:14 lists exactly what they desire: women, wealth, fine horses, land), but men whose prayer and zakāh survive that desire intact. ʿĀʾishah reported of the Prophet ﷺ: "he was in the service of his family, and when the time for prayer came, he would stand and go to pray" (Ṣaḥīḥ al-Bukhārī). The course is explicit that a hadith it also cites here — on marrying a man for his religion and character (at-Tirmidhī, Ibn Mājah) — "has some weakness in it," and says so rather than passing it off as ironclad.' },
        { label: 'Determination and reliance on Allah, held together — Q46:35, Q3:159', text: 'Q46:35 names the five Ulū al-ʿAzm ("men of firm determination") — Nūḥ, Ibrāhīm, Mūsā, ʿĪsā, and Muḥammad ﷺ — as evidence that resolve is itself a mark of the greatest men who ever lived. But Q3:159 pairs it immediately with tawakkul: decide firmly, then rely on Allah for the outcome. The course\'s formula: "resolve without reliance upon Allah is of no value, and fake reliance upon Allah with no determination and commitment is of no value" — a real man holds both without collapsing into either passivity or self-sufficiency.' },
        { label: "Independence — following advice without being ruled by it", text: 'Independence here doesn\'t mean refusing counsel — at Ḥudaybiyah the Prophet ﷺ took his wife Umm Salamah\'s political advice directly and acted on it. It means a man weighs advice and then makes his own decision rather than being pulled by every voice around him, illustrated by Abū Bakr\'s solitary, later-vindicated decision to fight those who withheld zakāh, and by Usāmah ibn Zayd commanding an army as a teenager. The Prophet ﷺ\'s own duʿāʾ for this: "O Allah, I ask You for steadfastness in all my affairs and determination in following the right path... I ask You for a sound heart and a truthful tongue" (an-Nasāʾī, at-Tirmidhī).' },
      ],
      qanda: [
        { q: "Why does the course insist manhood isn't 'a whole different set of behaviours' from what's asked of women generally?", a: "Because it grounds the whole course in ʿĀʾishah's report that \"women are nothing but the full sisters of men\" (Abū Dāwūd) — the underlying character (honesty, generosity, courage, gentleness) is the same standard for both; the course's actual project is describing how that one standard is specifically embodied and applied by a man, not inventing a rival ethic." },
        { q: 'Why does the course explicitly flag some of its own cited hadith as weak, rather than only citing strong ones?', a: "Because intellectual honesty about sourcing is treated as part of getting this right — the course names, for instance, that the marrying-for-religion hadith from at-Tirmidhī and Ibn Mājah \"has some weakness in it,\" modelling exactly the kind of transparent sourcing this collection tries to practise throughout, rather than quietly using only the citation without its caveat." },
      ],
    },
    {
      id: 'leadership-inner-strength', icon: '🧭', label: 'Leadership & Inner Strength', subtitle: 'Chapters 5–10 · Aspiration, Responsibility, Patience, Strength, Wisdom, Forbearance', color: 'var(--gold)',
      intro: "Six chapters build the internal architecture of leadership: aiming high, carrying responsibility for others, enduring hardship without breaking, understanding what strength actually is, thinking before acting, and not rushing to react. Ibn al-Qayyim's image opens it: \"if the star of aspiration rises in the darkness of the night of idleness, and this is combined with the moon of dedication, the earth will be lit up with the light of its Lord.\"",
      bullets: [
        { label: "High aspirations — Ṣaḥīḥ al-Bukhārī, Ṣaḥīḥ Muslim", text: 'The Prophet ﷺ taught: "if you ask Allah for anything, ask Him for al-Firdaws, for it is the best part of Paradise and the highest part of Paradise" (Ṣaḥīḥ al-Bukhārī) — aim as high as the request itself allows. This pairs with: "a strong believer is better and more beloved to Allah than a weak believer, and there is good in both. Be keen for that which benefits you... and if anything afflicts you, don\'t say \'if I had not done that, it would not have happened\'... for saying \'if only\' opens the door to the actions of the devil" (Ṣaḥīḥ Muslim). The Prophet ﷺ\'s own remedy for the laziness that kills aspiration: "O Allah, I seek refuge with You from worry and grief, from helplessness and laziness, from cowardice and stinginess, from being heavily in debt and from being overpowered by men" (Ṣaḥīḥ al-Bukhārī).' },
        { label: "Responsibility and leadership — Ṣaḥīḥ al-Bukhārī, Ṣaḥīḥ Muslim; Q2:286, Q4:34", text: '"Every one of you is a shepherd and everyone is answerable regarding his flock... a man is a guardian over the members of his family and will be questioned about them" (al-Bukhārī, Muslim) sits next to Q2:286 ("Allah does not burden a soul except within its capacity") and Q4:34 ("men are in charge of women by what Allah has given one over the other, and what they spend from their wealth") — the responsibility is real, but so is the built-in capacity to bear it. The course names both failure modes directly: shirking responsibility entirely, and abusing it like "a tyrant over his people." Real leadership isn\'t craved for its own sake either — the Prophet ﷺ told Abū Dharr, who wanted authority: "I see you to be weak, and I love for you what I love for myself, so do not rule over even two people" (Ṣaḥīḥ Muslim).' },
        { label: "Patience and resilience — Q38:44, Q3:200, Q31:17, Q90:4", text: 'Ayyūb (Job) is described as "an excellent servant... repeatedly turning back [in repentance]" despite his trial (Q38:44). Q3:200 commands ṣabr (patience within oneself), muṣābarah (patience with others), and murābaṭah (remaining stationed at one\'s post) together. Luqmān\'s advice to his son bundles prayer, commanding right, forbidding wrong, and patience into one verse as things "requiring determination" (Q31:17) — because, as Q90:4 puts it plainly, "We have created humankind in constant struggle."' },
        { label: "Strength — Ṣaḥīḥ al-Bukhārī, Ṣaḥīḥ Muslim", text: 'The course deliberately redefines the word before using it: "the strong one is not he who wrestles. The strong one is nothing more than the one who controls himself when angry" (al-Bukhārī, Muslim). A physically powerful man who "throws tantrums" in anger — divorcing his wife in a rage, forgetting what he\'s even said — has "fake masculinity," not real strength; physical fitness is genuinely encouraged, but only as an addition to self-control and īmān, never a substitute for them. "Whoever practises patience, Allah will make him patient" (al-Bukhārī).' },
        { label: 'Intelligence, wisdom, and forbearance — Q2:269, Q16:125; Ṣaḥīḥ Muslim', text: 'Q2:269 ("whoever has been given wisdom has certainly been given much good") and Q16:125 ("call to the way of your Lord with wisdom and good admonition") make wisdom a named prophetic trait, not an optional extra — "knowing when to show your strength and when to conceal it." This runs directly into forbearance (ḥilm): the Prophet ﷺ told Ashajj ʿAbd al-Qays, "you have two characteristics that Allah loves: forbearance and deliberation" — not rushing to revenge or holding grudges, and thinking before acting, both trained the same way knowledge is: "forbearance comes from practising forbearance."' },
      ],
      qanda: [
        { q: 'How does the "strong believer" hadith actually redefine strength, rather than simply praising physical power?', a: 'It explicitly names self-control in anger — not wrestling ability — as what "the strong one" means; the course uses this to distinguish real strength from the hyper-masculine performance of a man who is physically imposing but loses all composure and self-command the moment he is provoked.' },
        { q: 'Why does the course pair responsibility (Chapter 6) immediately with patience and resilience (Chapter 7)?', a: 'Because carrying real responsibility for others inevitably means absorbing hardship and difficult decisions without breaking — the course treats patience not as a separate virtue but as the direct precondition for being able to sustain the leadership and responsibility just described.' },
      ],
    },
    {
      id: 'honour-bravery-presence', icon: '🛡️', label: 'Honour, Bravery & Presence', subtitle: 'Chapters 11–15 · Defending the Weak, ʿIzzah, Haybah, Loyalty, and Courage', color: 'var(--burgundy-deep)',
      intro: "Five chapters on the more outward-facing virtues: standing up for people who can't stand up for themselves, honour correctly understood (not as domination), the harder-to-translate quality of haybah — a commanding presence — loyalty to one's word, and bravery properly defined as a strength of the heart rather than the absence of fear.",
      bullets: [
        { label: "Justice and defending the weak — Q28:23-24", text: 'Mūsā at the well of Madyan, watering the flocks of two women turned away by the other shepherds because "our father is an old man," is read as the template: shahāmah, a chivalry that combines leadership, patience, and readiness to help whoever needs it, with no expectation of reward — Mūsā\'s only remark afterward is "My Lord, indeed I am, for whatever good You would send down to me, in need" (Q28:24).' },
        { label: "Honour and dignity (al-ʿIzzah) — Q63:8, Q5:54, Q35:10", text: 'The course is careful to head off the obvious misreading first: ʿizzah is not "unrestricted might" or license to be "oppressive and lack consideration." Q63:8 states plainly that "all honour and power belongs to Allah, His Messenger, and the believers" — not seized, but granted. ʿUmar\'s own summary: "we are a people who were honoured by Allah through Islam. So whenever we seek honour in something else, Allah will disgrace us." Strength, in this framework, is "directed to the enemies of Allah," while "softness is directed towards the beloved of Allah" — the two are not in tension, they\'re aimed at different targets.' },
        { label: "Haybah — a commanding presence — Ṣaḥīḥ al-Bukhārī", text: 'Illustrated through ʿUmar ibn al-Khaṭṭāb: when he sought permission to enter and the women visiting the Prophet ﷺ scrambled to cover themselves at the mere sound of his voice, the Prophet ﷺ told him, "never does Satan find you going on a way, but he takes another way other than yours" (Ṣaḥīḥ al-Bukhārī). The course is explicit that haybah can curdle into arrogance and tyranny if it isn\'t built on taqwā — the correct version is what a student feels toward a serious teacher, built over years through īmān and enjoining right, not fear for its own sake; ʿUmar himself, the course stresses, was also known for deep care and kindness alongside this presence.' },
        { label: "Loyalty and trust — Q48:10, Q48:18, Q33:23, Q33:72, Q4:58", text: '"Those who pledge allegiance to you are actually pledging allegiance to Allah" (Q48:10) — loyalty to one\'s word is loyalty to Allah first. Q33:23 praises the Companions who "fulfilled their vow to the death" and "did not alter their commitment with any alteration," read as referring to those who vowed to fight again at Uḥud after missing Badr. Q33:72\'s image of the Trust (al-Amānah) — offered to the heavens, earth, and mountains, all of which declined it out of fear, before mankind took it on — frames every ordinary trust (a promise kept, a family cared for, an object returned) as carrying real weight. The Prophet ﷺ himself was known as al-Amīn, "the trustworthy one," before prophethood even began.' },
        { label: "Bravery and courage — Q33:10, Q33:65-66, Q2:190, Q8:45", text: 'Bravery is defined precisely: "the strength of the heart in times of severity" — not the absence of fear (the Companions themselves are described with "hearts reached the throats" from fear, Q33:10), but feet that stay firm despite it, and putting oneself in danger only "when there is a need for it," distinguished sharply from reckless stunts done for show. It develops through role models, through fearing Allah (which shrinks every other fear), through self-accountability, and through good company — "a man is upon the religion of his best friend, so let one of you look at whom he befriends." Q2:190\'s limit still applies: "do not exceed the limits. Allah does not like transgressors" — bravery bounded by the actual rules of engagement, not bravery as an excuse to break them.' },
      ],
      qanda: [
        { q: 'How does the course distinguish real haybah (presence) from simple intimidation or tyranny?', a: "By its source: the correct haybah is 'built from the taqwā of Allah' and develops over years through īmān and good character, the way a serious student feels appropriate restraint before a genuinely knowledgeable teacher — the corrupted version is a tyrant who inspires fear purely through cruelty and unpredictability, which the course explicitly names as not what Islam means by the term." },
        { q: 'Why does the course insist bravery is compatible with feeling fear, rather than requiring its absence?', a: "Because it cites the Companions themselves being described as having hearts that 'reached the throats' from fear (Q33:10) while still holding their position — the course's actual definition of bravery is firm feet despite fear, not the elimination of fear itself, which it calls a basic and unavoidable human trait." },
      ],
    },
    {
      id: 'softer-virtues', icon: '🌿', label: 'The Softer Virtues', subtitle: 'Chapters 16–20 · Gentleness, Generosity, Preferring Others, Courtesy, Shyness', color: 'var(--emerald)',
      intro: "Five chapters deliberately balance everything before them — the course's own stated aim is to correct the assumption that manhood is only strength, bravery, and haybah, by giving equal weight to gentleness, generosity, self-sacrifice, courteous restraint, and shyness, all illustrated through the Prophet ﷺ's own conduct.",
      bullets: [
        { label: "Gentleness and kindness — Q9:128, Q3:159; Ṣaḥīḥ Muslim, Ṣaḥīḥ al-Bukhārī", text: 'Q9:128 describes the Prophet ﷺ as one to whom "grievous is what you suffer... to the believers is kind and merciful." The course is explicit that bravery is never license for self-destruction — Q2:195\'s "do not let your own hands throw you into destruction" applies here too. The defining hadith: "gentleness was found in anything except that it made it beautiful, and it was never taken away from anything except that it made it ugly" (Ṣaḥīḥ Muslim). Told to be gentle with women specifically while driving camels carrying them, the Prophet ﷺ said simply: "be gentle" (Ṣaḥīḥ al-Bukhārī).' },
        { label: "Generosity and nobility (Karam) — Q51:26, Q3:92, Q2:274; Ṣaḥīḥ Muslim, Sunan Abī Dāwūd", text: 'Ibrāhīm\'s hospitality to his unrecognized guests — slipping away to bring "a fat roasted calf" without being asked — models generosity given without resentment (Q51:26). Q3:92 sets the standard high: "you will never achieve righteousness until you donate some of what you cherish." The story of the Prophet ﷺ giving away "a large flock" until the recipient told his people "Muhammad gives so much charity as if he has no fear of poverty" (Ṣaḥīḥ Muslim) is paired with Abū Bakr and ʿUmar\'s charity race — ʿUmar gave half his wealth thinking he\'d finally beaten Abū Bakr, only to learn Abū Bakr had given everything, leaving "Allah and His Messenger" for his own family (Sunan Abī Dāwūd).' },
        { label: "Preferring others (Īthār) — Q59:9", text: "Q59:9 praises the Anṣār who housed the Muhājirūn, feeling \"no desire in their hearts for whatever of the gains is given to the emigrants,\" giving preference \"even though they may be in need.\" Illustrated concretely: Ṭalḥah shielding the Prophet ﷺ with his own body at Uḥud until his fingers were paralysed by arrows (\"Paradise is a must for Ṭalḥah\"), and Abū Ṭalḥah al-Anṣārī positioning himself in the arrows' path saying only, \"my neck before your neck.\"" },
        { label: "Courtesy (Murūʾah) — Q7:199, Q25:63", text: 'Described as the complete standard of a man\'s manners — carefully avoiding anything permissible-but-blameworthy in the eyes of others, not only what Islam itself forbids. Sufyān ibn ʿUyaynah, asked whether murūʾah could be found in the Qurʾān, pointed to Q7:199: "be gracious, enjoin what is right, and turn away from those who act ignorantly." Q25:63 completes the picture: "the true servants of the Most Compassionate... when the foolish address them improperly, they only respond with peace."' },
        { label: 'Shyness (Ḥayāʾ) — a widely reported description, and a hadith on faith', text: 'Abū Saʿīd al-Khudrī described the Prophet ﷺ as having "more shyness than a virgin girl in her private room" — presented as direct proof that shyness is not a purely feminine trait, since the same Prophet ﷺ was also the most brave, strong, and commanding man described in the earlier chapters. "Shyness is always good," and — when an Anṣārī companion was rebuked by his brother for being "too shy" — the Prophet ﷺ intervened directly: "leave him, as shyness is a part of faith."' },
      ],
      qanda: [
        { q: "What is the course's own stated reason for spending five full chapters on gentleness, generosity, and shyness right after five chapters on bravery and honour?", a: "To correct a one-sided picture: the course states directly that it wants readers to take away 'the balance of characteristics' — that strength, haybah, and bravery mean nothing on their own, and that the same Prophet ﷺ held up as the model of courage and presence in earlier chapters was, in the same breath, described as more shy than a virgin girl and endlessly gentle." },
        { q: 'How does the story of Ṭalḥah and Abū Ṭalḥah at Uḥud illustrate īthār (preferring others) differently from ordinary generosity?', a: "Ordinary generosity gives away possessions; īthār here means physically absorbing harm meant for someone else — Ṭalḥah's paralysed fingers and Abū Ṭalḥah's repeated \"my neck before your neck\" both put the other person's safety ahead of their own body, which the course treats as the far end of the same spectrum that starts with simply sharing what one owns." },
      ],
    },
    {
      id: 'distinct-manhood-conclusion', icon: '🎯', label: 'Distinct Manhood & Putting It Into Practice', subtitle: 'Chapters 21–24 · Protective Jealousy, Matching Deeds to Words, Gender Distinction, and Raising the Next Generation', color: 'var(--grey-accent)',
      intro: "The closing chapters cover protective jealousy (ghayrah) rightly understood, the Qur'an's own warning against empty talk, the deliberate distinctness of masculine and feminine presentation, and — in the conclusion — concrete advice on actually raising boys with these characteristics rather than only describing them.",
      bullets: [
        { label: "Protective jealousy (Ghayrah) — Ṣaḥīḥ Muslim", text: 'Saʿd ibn ʿUbādah said he would strike a man found with his wife "with the sword, not with the flat part of it." Rather than rebuke this, the Prophet ﷺ responded: "are you surprised at Saʿd\'s protective jealousy? By Allah, I am more jealous of my honour than he, and Allah is more jealous than I. Because of His jealousy, Allah has prohibited indecency, both open and secret" (Ṣaḥīḥ Muslim). The course draws a hard line: this is not the jealousy of suspicion or resentment at someone else\'s good fortune — a man who feels nothing when his wife is treated indecently is named directly as a dayyūth, "a despicable example of a human being," while a man who genuinely cares protects rather than controls.' },
        { label: "Deeds matching words — Q61:2-3, Q26:224-227", text: 'Q61:2-3 is blunt: "why do you say that which you do not do? Most hateful it is with Allah that you say that which you do not do." Q26:224-227 extends this to poets specifically, who "say what they do not do" — except those who "believe and do righteous deeds." The course notes some pre-Islamic poets were killed by enemies who called their bluff on boasts about their own swordsmanship — a cautionary illustration that a real man is measured by what he does, not by what he claims about himself.' },
        { label: 'Appearing distinct from women', text: 'Ibn ʿAbbās reported that "Allah\'s Messenger ﷺ cursed the men that resembled women and the women that resembled men." The course frames this as one more instance of the same balance running through the whole course: Islam gives men and women genuinely distinct presentations and roles, "and there is immense good in both" — not a hierarchy of worth, but a refusal to collapse the distinction entirely in either direction.' },
        { label: 'Putting it into practice — three concrete steps', text: 'The conclusion turns from description to method: (1) knowledge — pairing these traits with religious understanding, since "those who were best in Jāhiliyyah are best in Islam, if they have religious understanding"; (2) companionship — deliberately surrounding oneself and one\'s children with people who take generosity, justice, and good character seriously; and (3) an explicit argument against "cotton wool parenting" — citing Q4:6\'s instruction to "test the competence of orphans" and Q29:20\'s "travel throughout the land" as evidence that measured risk and real independence (camping, travel, first aid, being briefly out of one\'s comfort zone) are what actually build these characteristics, rather than lectures alone. The course\'s closing diagnosis: boys denied this kind of tarbiyah don\'t become characterless by accident — they go looking for identity in "gang culture," online influencers, and glorified violence instead.' },
      ],
      qanda: [
        { q: "How does the course distinguish healthy ghayrah (protective jealousy) from controlling or possessive behaviour?", a: "By its target and its root: ghayrah as praised in the hadith is about caring enough to protect someone's honour and safety, modelled on Allah's own prohibition of indecency — the course explicitly rejects 'the jealousy of suspicion' or resentment, and names the opposite failure (feeling nothing when a wife or family member is treated indecently) as the real disgrace, not an excess of care." },
        { q: "Why does the conclusion argue against 'cotton wool parenting' using verses about testing orphans and travelling, rather than a hadith about bravery specifically?", a: "Because the point is method, not just motivation — Q4:6 and Q29:20 are cited as Qur'anic precedent for deliberately giving young people responsibility and unfamiliar situations rather than shielding them from all risk, which the course argues is how traits like independence, bravery, and resourcefulness are actually built, not simply described in a lesson." },
      ],
    },
    {
      id: 'quizzes', icon: '🧠', label: 'Quizzes', subtitle: 'All Questions From the Sections Above, in One Place', color: 'var(--gold)',
      intro: 'Every quiz question from the five sections above — pooled here in one combined quiz, in the same order as the sections themselves.',
      quiz: [
        { q: 'According to the course, what are named as some of the causes behind today\'s crisis in masculinity?', choices: ['Only video games', 'An ideological war against masculinity, a hyper-masculine counter-culture, family breakdown, and loss of religious knowledge', 'Nothing — the course claims there is no real crisis', 'Only the influence of pre-Islamic poetry'], correct: 1 },
        { q: 'What does ʿĀʾishah\'s hadith "women are nothing but the full sisters of men" establish about this course\'s whole approach?', choices: ['That men and women require entirely separate moral codes', 'That the same underlying character is being examined specifically through how a man embodies it, not a rival ethic', 'That the hadith is unrelated to the topic', 'That women are exempt from the traits discussed'], correct: 1 },
        { q: 'What does the course say about the hadith on marrying a man for his religion and character, cited from at-Tirmidhī and Ibn Mājah?', choices: ['That it is definitely authentic with no issues', 'That it "has some weakness in it" — stated directly rather than omitted', 'That it was fabricated entirely', 'That it does not appear in this course at all'], correct: 1 },
        { q: 'According to Q46:35, who are the Ulū al-ʿAzm, the "men of firm determination"?', choices: ['All the prophets equally', 'Nūḥ, Ibrāhīm, Mūsā, ʿĪsā, and Muḥammad ﷺ', 'Only the four rightly-guided caliphs', 'The seventy people of Maʿaznah'], correct: 1 },
        { q: 'What does the hadith "the strong one is not he who wrestles" actually redefine strength as?', choices: ['Physical size alone', 'Wealth and social status', 'Controlling oneself when angry', 'Winning arguments'], correct: 2 },
        { q: 'What did the Prophet ﷺ tell Abū Dharr when he wanted a position of authority?', choices: ['That he was the most qualified person available', 'That he was "weak" and should not rule over even two people', 'That he must first complete years of training', 'That authority was forbidden to him permanently'], correct: 1 },
        { q: 'What three things does Q3:200 command together?', choices: ['Wealth, health, and knowledge', 'Ṣabr (patience within oneself), muṣābarah (patience with others), and murābaṭah (remaining stationed at one\'s post)', 'Marriage, children, and land', 'Travel, trade, and study'], correct: 1 },
        { q: 'According to the course, what is ʿizzah (honour) explicitly NOT, despite a common misconception?', choices: ['A quality granted only to prophets', 'Unrestricted might used to oppress or dominate others', 'A purely spiritual concept with no real-world expression', 'Something Islam discourages entirely'], correct: 1 },
        { q: 'What did the Prophet ﷺ say to ʿUmar after the women visiting him quickly covered themselves at the sound of his voice?', choices: ['That ʿUmar should be gentler with people', 'That Satan takes a different path than the one ʿUmar is walking', 'That the women were being unreasonable', 'Nothing — he said nothing in response'], correct: 1 },
        { q: 'How does the course define bravery, distinct from simple fearlessness?', choices: ['The complete absence of fear in any situation', 'The strength of the heart in times of severity — feet remaining firm despite fear, not the absence of it', 'Physical size and muscular strength', 'Never backing down from any confrontation, regardless of need'], correct: 1 },
        { q: 'What defining hadith is used to introduce gentleness in this course?', choices: ['"Gentleness was found in anything except that it made it beautiful, and it was never taken away from anything except that it made it ugly"', '"A strong believer is better than a weak believer"', '"Actions are judged by intentions"', '"The believers are like one body"'], correct: 0 },
        { q: 'What did Abū Bakr give during the charity competition with ʿUmar, according to Sunan Abī Dāwūd?', choices: ['Nothing that day', 'Half of his wealth', 'Everything he had, leaving only Allah and His Messenger for his family', 'A single sheep'], correct: 2 },
        { q: 'What did Ṭalḥah do at the Battle of Uḥud that the course cites as an example of īthār (preferring others)?', choices: ['He retreated to protect himself', 'He shielded the Prophet ﷺ with his own body until his fingers were paralysed by arrows', 'He gave away his weapon to another soldier', 'He negotiated a truce'], correct: 1 },
        { q: 'According to Sufyān ibn ʿUyaynah, where can murūʾah (courtesy) be found in the Qurʾān?', choices: ['It cannot be found in the Qurʾān at all', 'In Q7:199: "be gracious, enjoin what is right, and turn away from those who act ignorantly"', 'Only in the stories of the prophets', 'In a verse about trade and commerce'], correct: 1 },
        { q: 'How did Abū Saʿīd al-Khudrī describe the Prophet ﷺ\'s shyness?', choices: ['That he had almost no sense of shyness', 'That he had more shyness than a virgin girl in her private room', 'That shyness was a weakness he worked to overcome', 'That it only appeared in his youth'], correct: 1 },
        { q: 'What did the Prophet ﷺ say in response to Saʿd ibn ʿUbādah\'s statement about striking a man found with his wife?', choices: ['That Saʿd was being excessive and should calm down', 'That he himself was more jealous of his honour than Saʿd, and Allah is more jealous still', 'That such jealousy has no place in Islam', 'That Saʿd should divorce his wife instead'], correct: 1 },
        { q: 'According to the course, what does the Qurʾān say happened to some poets who boasted about their own swordsmanship without matching action?', choices: ['They became wealthy from their poetry', 'Some lost their lives when enemies called their bluff', 'They were universally celebrated regardless', 'The Qurʾān does not address poets at all'], correct: 1 },
        { q: 'What does the course cite Q4:6 ("test the competence of the orphans") and Q29:20 ("travel throughout the land") as evidence for?', choices: ['That travel is religiously obligatory', 'That deliberately giving young people responsibility and measured risk — not "cotton wool parenting" — is how independence and resilience are actually built', 'That orphans should not be tested at all', 'That these verses are unrelated to raising children'], correct: 1 },
        { q: 'What term does the course use for a man who feels nothing when his wife or family is treated indecently, and calls "a despicable example of a human being"?', choices: ['Muḥsin', 'Dayyūth', 'Ṣābir', 'Karīm'], correct: 1 },
        { q: 'What does Ibn ʿAbbās report the Prophet ﷺ said about men and women resembling one another?', choices: ['That it should be encouraged as a sign of equality', 'That Allah\'s Messenger ﷺ cursed men who resembled women and women who resembled men', 'That the Prophet ﷺ never addressed the topic', 'That it depends entirely on personal preference'], correct: 1 },
      ],
    },
  ]
});
